// Deck 4 — Hebrew / Israeli deck: curated well-known Israeli songs
// Titles + artists in Hebrew script for best Deezer match rate.
// `year` = original release year (drives the timeline gameplay).
// Same shape as the other decks: { title, artist, year }

const SONGS4 = [
  // ── זמר עברי קלאסי ושנות ה-60-70 ─────────────────────────────────────────────
  { title: "ירושלים של זהב", artist: "שולי נתן", year: 1967 },
  { title: "לו יהי", artist: "חוה אלברשטיין", year: 1973 },
  { title: "אני ואתה", artist: "אריק איינשטיין", year: 1971 },
  { title: "סע לאט", artist: "אריק איינשטיין", year: 1974 },
  { title: "עוף גוזל", artist: "אריק איינשטיין", year: 1987 },
  { title: "עטור מצחך", artist: "אריק איינשטיין", year: 1977 },
  { title: "יו יה", artist: "כוורת", year: 1973 },
  { title: "נתתי לה חיי", artist: "כוורת", year: 1974 },
  { title: "שיר המכולת", artist: "כוורת", year: 1973 },
  { title: "היא כל כך יפה", artist: "כוורת", year: 1975 },
  { title: "גוליית", artist: "כוורת", year: 1975 },
  { title: "הללויה", artist: "חלב ודבש", year: 1979 },
  { title: "אבניבי", artist: "יזהר כהן", year: 1978 },
  { title: "בשנה הבאה", artist: "אילנית", year: 1970 },
  { title: "שיר לשלום", artist: "מירי אלוני", year: 1969 },
  { title: "אהבה בסוף הקיץ", artist: "צביקה פיק", year: 1977 },
  { title: "מרי לו", artist: "צביקה פיק", year: 1978 },
  { title: "הרקדן האוטומטי", artist: "צביקה פיק", year: 1973 },

  // ── שנות ה-80 ─────────────────────────────────────────────────────────────
  { title: "מחכים למשיח", artist: "שלום חנוך", year: 1985 },
  { title: "רק בן אדם", artist: "שלום חנוך", year: 1988 },
  { title: "לילה", artist: "שלום חנוך", year: 1970 },
  { title: "רכבת לילה לקהיר", artist: "משינה", year: 1985 },
  { title: "שלח לי מלאך", artist: "משינה", year: 1987 },
  { title: "אהובתי", artist: "משינה", year: 1987 },
  { title: "האגס 1", artist: "אהוד בנאי", year: 1989 },
  { title: "עיר מקלט", artist: "אהוד בנאי", year: 1987 },
  { title: "טיפ טיפה", artist: "זהבה בן", year: 1992 },
  { title: "עיניים שלי", artist: "יהודה פוליקר", year: 1985 },
  { title: "אפר ואבק", artist: "יהודה פוליקר", year: 1988 },
  { title: "שביל הבריחה", artist: "ריטה", year: 1986 },
  { title: "באה מאהבה", artist: "יהודית רביץ", year: 1987 },
  { title: "הילדה הכי יפה בגן", artist: "יהודית רביץ", year: 1978 },
  { title: "צליל מכוון", artist: "יצחק קלפטר", year: 1979 },
  { title: "הפרח בגני", artist: "זוהר ארגוב", year: 1982 },
  { title: "אלינור", artist: "זוהר ארגוב", year: 1980 },
  { title: "אם ננעלו", artist: "עפרה חזה", year: 1984 },
  { title: "גלבי", artist: "עפרה חזה", year: 1984 },
  { title: "אין לי ארץ אחרת", artist: "גלי עטרי", year: 1986 },
  { title: "אנשים טובים באמצע הדרך", artist: "נעמי שמר", year: 1981 },
  { title: "פנים אל פנים", artist: "בנזין", year: 1982 },
  { title: "אצל הדודה והדוד", artist: "דני סנדרסון", year: 1987 },
  { title: "גלשן", artist: "דני סנדרסון", year: 1982 },
  { title: "רדיו חזק", artist: "תיסלם", year: 1981 },
  { title: "לראות אותה היום", artist: "תיסלם", year: 1981 },
  { title: "בוקר של כיף", artist: "תיסלם", year: 1981 },

  // ── שנות ה-90 ─────────────────────────────────────────────────────────────
  { title: "הכוכבים דולקים על אש קטנה", artist: "משינה", year: 1990 },
  { title: "ערב כחול עמוק", artist: "ריטה", year: 1994 },
  { title: "תותים", artist: "אתניקס", year: 1992 },
  { title: "ג'סיקה", artist: "אתניקס", year: 1993 },
  { title: "התחנה הישנה", artist: "טיפקס", year: 1995 },
  { title: "עכשיו מעונן", artist: "אביב גפן", year: 1993 },
  { title: "האם להיות בך מאוהב", artist: "אביב גפן", year: 1994 },
  { title: "השיר שלנו", artist: "אביב גפן", year: 1995 },
  { title: "זן נדיר", artist: "קורין אלאל", year: 1992 },
  { title: "אנטארקטיקה", artist: "קורין אלאל", year: 1989 },
  { title: "אלה", artist: "היהודים", year: 1995 },
  { title: "קח אותי", artist: "היהודים", year: 1995 },
  { title: "הימים שלנו", artist: "היהודים", year: 1995 },
  { title: "מכה אפורה", artist: "מוניקה סקס", year: 1995 },
  { title: "על הרצפה", artist: "מוניקה סקס", year: 1995 },
  { title: "דמעות", artist: "אייל גולן", year: 1998 },
  { title: "יפה שלי", artist: "אייל גולן", year: 1998 },
  { title: "אגדות", artist: "עברי לידר", year: 1997 },
  { title: "מרי לנצח", artist: "עברי לידר", year: 1997 },
  { title: "הכוס הכחולה", artist: "עברי לידר", year: 1999 },

  // ── שנות ה-2000 וה-2010 ───────────────────────────────────────────────────
  { title: "משהו קטן וטוב", artist: "משינה", year: 2003 },
  { title: "היום", artist: "אהוד בנאי", year: 2004 },
  { title: "שירת הסטיקר", artist: "הדג נחש", year: 2004 },
  { title: "מדברים על שלום", artist: "מוקי", year: 2001 },
  { title: "שמש", artist: "חנן בן ארי", year: 2019 },
  { title: "אלוף העולם", artist: "חנן בן ארי", year: 2019 },
  { title: "ויקיפדיה", artist: "חנן בן ארי", year: 2017 },
  { title: "סיגפו", artist: "בית הבובות", year: 2005 },
  { title: "שיר בעיפרון", artist: "בית הבובות", year: 2005 },
  { title: "לבן בחלום שחור", artist: "איפה הילד", year: 1994 },
  { title: "גשם", artist: "מאיר בנאי", year: 1987 },
  { title: "שער הרחמים", artist: "מאיר בנאי", year: 1992 },
  { title: "אהבה קצרה", artist: "מאיר בנאי", year: 1992 },
  { title: "Toy", artist: "נטע ברזילי", year: 2018 },
  { title: "שמישהו יעצור אותי", artist: "עדן חסון", year: 2017 },
  { title: "מלכת השושנים", artist: "עדן בן זקן", year: 2015 },
  { title: "תל אביב", artist: "עומר אדם", year: 2013 },
  { title: "שני משוגעים", artist: "עומר אדם", year: 2018 },
  { title: "דרך השלום", artist: "פאר טסי", year: 2014 },
  { title: "טודו בום", artist: "סטטיק ובן אל תבורי", year: 2017 },
  { title: "זהב", artist: "סטטיק ובן אל תבורי", year: 2017 },
  { title: "ממעמקים", artist: "הפרויקט של עידן רייכל", year: 2004 },
  { title: "בואי", artist: "הפרויקט של עידן רייכל", year: 2002 },
  { title: "אור גדול", artist: "אמיר דדון", year: 2010 },
  { title: "דרכנו", artist: "חני פירסטנברג ושרית וינו-אלעד", year: 2001 },
  { title: "תגידי שטוב", artist: "כנסיית השכל", year: 2001 },
  { title: "אתה תותח", artist: "שרית חדד", year: 2002 },
  { title: "כשהלב בוכה", artist: "שרית חדד", year: 2001 },
  { title: "צליל מיתר", artist: "אייל גולן", year: 2001 },
  { title: "מלכת היופי שלי", artist: "אייל גולן", year: 2005 },
  { title: "בוא", artist: "עברי לידר", year: 2002 },

  // ── שנות ה-2020 ────────────────────────────────────────────────────────────
  { title: "מסיבה", artist: "יסמין מועלם", year: 2020 },
  { title: "יחפים", artist: "יסמין מועלם", year: 2021 },
  { title: "לך לישון", artist: "אנה זק", year: 2022 },
  { title: "Unicorn", artist: "נועה קירל", year: 2023 },
  { title: "פנתרה", artist: "נועה קירל", year: 2022 },
  { title: "מיליון דולר", artist: "נועה קירל", year: 2020 }
];

module.exports = SONGS4;
