// Deck 3 — Rock Deck: 300+ well-known English-language rock songs
// Spans classic rock, hard rock, glam metal, grunge, alt, punk, 2000s/2010s rock

const SONGS3 = [
  // ── The Beatles ───────────────────────────────────────────────────────────
  { title: "Helter Skelter", artist: "The Beatles", year: 1968 },
  { title: "Revolution", artist: "The Beatles", year: 1968 },
  { title: "Day Tripper", artist: "The Beatles", year: 1965 },
  { title: "Come Together", artist: "The Beatles", year: 1969 },
  { title: "Back in the U.S.S.R.", artist: "The Beatles", year: 1968 },
  { title: "Twist and Shout", artist: "The Beatles", year: 1963 },
  { title: "A Hard Day's Night", artist: "The Beatles", year: 1964 },
  { title: "Get Back", artist: "The Beatles", year: 1969 },
  { title: "Paperback Writer", artist: "The Beatles", year: 1966 },
  { title: "Ticket to Ride", artist: "The Beatles", year: 1965 },

  // ── The Rolling Stones ────────────────────────────────────────────────────
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
  { title: "Sympathy for the Devil", artist: "The Rolling Stones", year: 1968 },
  { title: "Gimme Shelter", artist: "The Rolling Stones", year: 1969 },
  { title: "Brown Sugar", artist: "The Rolling Stones", year: 1971 },
  { title: "Wild Horses", artist: "The Rolling Stones", year: 1971 },
  { title: "Start Me Up", artist: "The Rolling Stones", year: 1981 },
  { title: "Angie", artist: "The Rolling Stones", year: 1973 },
  { title: "Honky Tonk Women", artist: "The Rolling Stones", year: 1969 },
  { title: "Miss You", artist: "The Rolling Stones", year: 1978 },
  { title: "Jumpin' Jack Flash", artist: "The Rolling Stones", year: 1968 },
  { title: "You Can't Always Get What You Want", artist: "The Rolling Stones", year: 1969 },
  { title: "19th Nervous Breakdown", artist: "The Rolling Stones", year: 1966 },

  // ── Led Zeppelin ──────────────────────────────────────────────────────────
  { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
  { title: "Whole Lotta Love", artist: "Led Zeppelin", year: 1969 },
  { title: "Kashmir", artist: "Led Zeppelin", year: 1975 },
  { title: "Black Dog", artist: "Led Zeppelin", year: 1971 },
  { title: "Immigrant Song", artist: "Led Zeppelin", year: 1970 },
  { title: "Rock and Roll", artist: "Led Zeppelin", year: 1971 },
  { title: "Going to California", artist: "Led Zeppelin", year: 1971 },
  { title: "Ramble On", artist: "Led Zeppelin", year: 1969 },
  { title: "When the Levee Breaks", artist: "Led Zeppelin", year: 1971 },
  { title: "Good Times Bad Times", artist: "Led Zeppelin", year: 1969 },
  { title: "Communication Breakdown", artist: "Led Zeppelin", year: 1969 },
  { title: "Dazed and Confused", artist: "Led Zeppelin", year: 1969 },
  { title: "Heartbreaker", artist: "Led Zeppelin", year: 1969 },
  { title: "Achilles Last Stand", artist: "Led Zeppelin", year: 1976 },

  // ── The Who ───────────────────────────────────────────────────────────────
  { title: "Baba O'Riley", artist: "The Who", year: 1971 },
  { title: "Won't Get Fooled Again", artist: "The Who", year: 1971 },
  { title: "My Generation", artist: "The Who", year: 1965 },
  { title: "Pinball Wizard", artist: "The Who", year: 1969 },
  { title: "Behind Blue Eyes", artist: "The Who", year: 1971 },
  { title: "Who Are You", artist: "The Who", year: 1978 },
  { title: "Substitute", artist: "The Who", year: 1966 },
  { title: "I Can See for Miles", artist: "The Who", year: 1967 },
  { title: "Love Reign O'er Me", artist: "The Who", year: 1973 },
  { title: "The Real Me", artist: "The Who", year: 1973 },

  // ── The Doors ─────────────────────────────────────────────────────────────
  { title: "Light My Fire", artist: "The Doors", year: 1967 },
  { title: "Riders on the Storm", artist: "The Doors", year: 1971 },
  { title: "Break On Through (To the Other Side)", artist: "The Doors", year: 1967 },
  { title: "People Are Strange", artist: "The Doors", year: 1967 },
  { title: "Hello, I Love You", artist: "The Doors", year: 1968 },
  { title: "Roadhouse Blues", artist: "The Doors", year: 1970 },
  { title: "L.A. Woman", artist: "The Doors", year: 1971 },
  { title: "Touch Me", artist: "The Doors", year: 1968 },
  { title: "The End", artist: "The Doors", year: 1967 },
  { title: "When the Music's Over", artist: "The Doors", year: 1967 },

  // ── Pink Floyd ────────────────────────────────────────────────────────────
  { title: "Comfortably Numb", artist: "Pink Floyd", year: 1979 },
  { title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
  { title: "Money", artist: "Pink Floyd", year: 1973 },
  { title: "Time", artist: "Pink Floyd", year: 1973 },
  { title: "Another Brick in the Wall, Pt. 2", artist: "Pink Floyd", year: 1979 },
  { title: "Shine On You Crazy Diamond", artist: "Pink Floyd", year: 1975 },
  { title: "Have a Cigar", artist: "Pink Floyd", year: 1975 },
  { title: "Hey You", artist: "Pink Floyd", year: 1979 },
  { title: "Run Like Hell", artist: "Pink Floyd", year: 1979 },
  { title: "Brain Damage", artist: "Pink Floyd", year: 1973 },
  { title: "Us and Them", artist: "Pink Floyd", year: 1973 },
  { title: "Dogs", artist: "Pink Floyd", year: 1977 },
  { title: "Pigs (Three Different Ones)", artist: "Pink Floyd", year: 1977 },
  { title: "Welcome to the Machine", artist: "Pink Floyd", year: 1975 },

  // ── CCR ───────────────────────────────────────────────────────────────────
  { title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Proud Mary", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Have You Ever Seen the Rain", artist: "Creedence Clearwater Revival", year: 1971 },
  { title: "Bad Moon Rising", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Born on the Bayou", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Down on the Corner", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Up Around the Bend", artist: "Creedence Clearwater Revival", year: 1970 },

  // ── Hendrix / Joplin / Cream / Kinks ──────────────────────────────────────
  { title: "Purple Haze", artist: "Jimi Hendrix", year: 1967 },
  { title: "All Along the Watchtower", artist: "Jimi Hendrix", year: 1968 },
  { title: "Voodoo Child (Slight Return)", artist: "Jimi Hendrix", year: 1968 },
  { title: "Hey Joe", artist: "Jimi Hendrix", year: 1966 },
  { title: "Foxy Lady", artist: "Jimi Hendrix", year: 1967 },
  { title: "Little Wing", artist: "Jimi Hendrix", year: 1967 },
  { title: "Crosstown Traffic", artist: "Jimi Hendrix", year: 1968 },
  { title: "Piece of My Heart", artist: "Janis Joplin", year: 1968 },
  { title: "Me and Bobby McGee", artist: "Janis Joplin", year: 1971 },
  { title: "Cry Baby", artist: "Janis Joplin", year: 1971 },
  { title: "Sunshine of Your Love", artist: "Cream", year: 1967 },
  { title: "White Room", artist: "Cream", year: 1968 },
  { title: "Crossroads", artist: "Cream", year: 1968 },
  { title: "You Really Got Me", artist: "The Kinks", year: 1964 },
  { title: "Lola", artist: "The Kinks", year: 1970 },
  { title: "Waterloo Sunset", artist: "The Kinks", year: 1967 },
  { title: "All Day and All of the Night", artist: "The Kinks", year: 1964 },

  // ── Aerosmith ─────────────────────────────────────────────────────────────
  { title: "Dream On", artist: "Aerosmith", year: 1973 },
  { title: "Sweet Emotion", artist: "Aerosmith", year: 1975 },
  { title: "Walk This Way", artist: "Aerosmith", year: 1975 },
  { title: "Back in the Saddle", artist: "Aerosmith", year: 1976 },
  { title: "Toys in the Attic", artist: "Aerosmith", year: 1975 },
  { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", year: 1998 },
  { title: "Crazy", artist: "Aerosmith", year: 1993 },
  { title: "Cryin'", artist: "Aerosmith", year: 1993 },
  { title: "Janie's Got a Gun", artist: "Aerosmith", year: 1989 },
  { title: "Livin' on the Edge", artist: "Aerosmith", year: 1993 },
  { title: "Love in an Elevator", artist: "Aerosmith", year: 1989 },

  // ── Queen ─────────────────────────────────────────────────────────────────
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "We Will Rock You", artist: "Queen", year: 1977 },
  { title: "We Are the Champions", artist: "Queen", year: 1977 },
  { title: "Don't Stop Me Now", artist: "Queen", year: 1978 },
  { title: "Killer Queen", artist: "Queen", year: 1974 },
  { title: "Somebody to Love", artist: "Queen", year: 1976 },
  { title: "Radio Ga Ga", artist: "Queen", year: 1984 },
  { title: "Under Pressure", artist: "Queen & David Bowie", year: 1981 },
  { title: "Crazy Little Thing Called Love", artist: "Queen", year: 1979 },
  { title: "Fat Bottomed Girls", artist: "Queen", year: 1978 },
  { title: "Another One Bites the Dust", artist: "Queen", year: 1980 },
  { title: "Tie Your Mother Down", artist: "Queen", year: 1976 },
  { title: "Hammer to Fall", artist: "Queen", year: 1984 },
  { title: "Princes of the Universe", artist: "Queen", year: 1986 },
  { title: "The Show Must Go On", artist: "Queen", year: 1991 },

  // ── Eagles / Lynyrd / Boston / Kansas / Rush / Yes / Genesis / Sabbath ────
  { title: "Hotel California", artist: "Eagles", year: 1976 },
  { title: "Take It Easy", artist: "Eagles", year: 1972 },
  { title: "Desperado", artist: "Eagles", year: 1973 },
  { title: "Lyin' Eyes", artist: "Eagles", year: 1975 },
  { title: "Life in the Fast Lane", artist: "Eagles", year: 1976 },
  { title: "One of These Nights", artist: "Eagles", year: 1975 },
  { title: "Witchy Woman", artist: "Eagles", year: 1972 },
  { title: "Heartache Tonight", artist: "Eagles", year: 1979 },
  { title: "New Kid in Town", artist: "Eagles", year: 1976 },
  { title: "Free Bird", artist: "Lynyrd Skynyrd", year: 1973 },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974 },
  { title: "Simple Man", artist: "Lynyrd Skynyrd", year: 1973 },
  { title: "Tuesday's Gone", artist: "Lynyrd Skynyrd", year: 1973 },
  { title: "Gimme Three Steps", artist: "Lynyrd Skynyrd", year: 1973 },
  { title: "More Than a Feeling", artist: "Boston", year: 1976 },
  { title: "Don't Look Back", artist: "Boston", year: 1978 },
  { title: "Foreplay/Long Time", artist: "Boston", year: 1976 },
  { title: "Peace of Mind", artist: "Boston", year: 1976 },
  { title: "Smokin'", artist: "Boston", year: 1976 },
  { title: "Carry On Wayward Son", artist: "Kansas", year: 1976 },
  { title: "Dust in the Wind", artist: "Kansas", year: 1977 },
  { title: "Point of Know Return", artist: "Kansas", year: 1977 },
  { title: "Tom Sawyer", artist: "Rush", year: 1981 },
  { title: "The Spirit of Radio", artist: "Rush", year: 1980 },
  { title: "Limelight", artist: "Rush", year: 1981 },
  { title: "YYZ", artist: "Rush", year: 1981 },
  { title: "Closer to the Heart", artist: "Rush", year: 1977 },
  { title: "Fly by Night", artist: "Rush", year: 1975 },
  { title: "Working Man", artist: "Rush", year: 1974 },
  { title: "Roundabout", artist: "Yes", year: 1971 },
  { title: "Owner of a Lonely Heart", artist: "Yes", year: 1983 },
  { title: "Long Distance Runaround", artist: "Yes", year: 1971 },
  { title: "Invisible Touch", artist: "Genesis", year: 1986 },
  { title: "Land of Confusion", artist: "Genesis", year: 1986 },
  { title: "Follow You Follow Me", artist: "Genesis", year: 1978 },
  { title: "That's All", artist: "Genesis", year: 1983 },
  { title: "Iron Man", artist: "Black Sabbath", year: 1970 },
  { title: "Paranoid", artist: "Black Sabbath", year: 1970 },
  { title: "War Pigs", artist: "Black Sabbath", year: 1970 },
  { title: "N.I.B.", artist: "Black Sabbath", year: 1970 },
  { title: "Sweet Leaf", artist: "Black Sabbath", year: 1971 },
  { title: "Sabbath Bloody Sabbath", artist: "Black Sabbath", year: 1973 },
  { title: "Heaven and Hell", artist: "Black Sabbath", year: 1980 },

  // ── AC/DC ─────────────────────────────────────────────────────────────────
  { title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { title: "Back in Black", artist: "AC/DC", year: 1980 },
  { title: "Thunderstruck", artist: "AC/DC", year: 1990 },
  { title: "You Shook Me All Night Long", artist: "AC/DC", year: 1980 },
  { title: "T.N.T.", artist: "AC/DC", year: 1975 },
  { title: "Hells Bells", artist: "AC/DC", year: 1980 },
  { title: "Dirty Deeds Done Dirt Cheap", artist: "AC/DC", year: 1976 },
  { title: "For Those About to Rock (We Salute You)", artist: "AC/DC", year: 1981 },
  { title: "Whole Lotta Rosie", artist: "AC/DC", year: 1977 },
  { title: "Rock and Roll Ain't Noise Pollution", artist: "AC/DC", year: 1980 },

  // ── Guns N' Roses ─────────────────────────────────────────────────────────
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "November Rain", artist: "Guns N' Roses", year: 1991 },
  { title: "Welcome to the Jungle", artist: "Guns N' Roses", year: 1987 },
  { title: "Paradise City", artist: "Guns N' Roses", year: 1987 },
  { title: "Patience", artist: "Guns N' Roses", year: 1988 },
  { title: "Don't Cry", artist: "Guns N' Roses", year: 1991 },
  { title: "Knockin' on Heaven's Door", artist: "Guns N' Roses", year: 1991 },
  { title: "You Could Be Mine", artist: "Guns N' Roses", year: 1991 },
  { title: "Mr. Brownstone", artist: "Guns N' Roses", year: 1987 },
  { title: "Civil War", artist: "Guns N' Roses", year: 1991 },
  { title: "Estranged", artist: "Guns N' Roses", year: 1991 },

  // ── Bon Jovi / Van Halen / Def Leppard / Mötley Crüe ──────────────────────
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "You Give Love a Bad Name", artist: "Bon Jovi", year: 1986 },
  { title: "Wanted Dead or Alive", artist: "Bon Jovi", year: 1986 },
  { title: "Always", artist: "Bon Jovi", year: 1994 },
  { title: "It's My Life", artist: "Bon Jovi", year: 2000 },
  { title: "Bad Medicine", artist: "Bon Jovi", year: 1988 },
  { title: "Born to Be My Baby", artist: "Bon Jovi", year: 1988 },
  { title: "Bed of Roses", artist: "Bon Jovi", year: 1992 },
  { title: "Have a Nice Day", artist: "Bon Jovi", year: 2005 },
  { title: "Jump", artist: "Van Halen", year: 1984 },
  { title: "Panama", artist: "Van Halen", year: 1984 },
  { title: "Hot for Teacher", artist: "Van Halen", year: 1984 },
  { title: "Eruption", artist: "Van Halen", year: 1978 },
  { title: "Runnin' with the Devil", artist: "Van Halen", year: 1978 },
  { title: "Why Can't This Be Love", artist: "Van Halen", year: 1986 },
  { title: "Right Now", artist: "Van Halen", year: 1991 },
  { title: "Dance the Night Away", artist: "Van Halen", year: 1979 },
  { title: "You Really Got Me", artist: "Van Halen", year: 1978 },
  { title: "Pour Some Sugar on Me", artist: "Def Leppard", year: 1987 },
  { title: "Photograph", artist: "Def Leppard", year: 1983 },
  { title: "Hysteria", artist: "Def Leppard", year: 1987 },
  { title: "Love Bites", artist: "Def Leppard", year: 1987 },
  { title: "Animal", artist: "Def Leppard", year: 1987 },
  { title: "Rocket", artist: "Def Leppard", year: 1987 },
  { title: "Foolin'", artist: "Def Leppard", year: 1983 },
  { title: "Kickstart My Heart", artist: "Mötley Crüe", year: 1989 },
  { title: "Home Sweet Home", artist: "Mötley Crüe", year: 1985 },
  { title: "Dr. Feelgood", artist: "Mötley Crüe", year: 1989 },
  { title: "Girls, Girls, Girls", artist: "Mötley Crüe", year: 1987 },
  { title: "Wild Side", artist: "Mötley Crüe", year: 1987 },
  { title: "Shout at the Devil", artist: "Mötley Crüe", year: 1983 },

  // ── Iron Maiden / Judas Priest ────────────────────────────────────────────
  { title: "Run to the Hills", artist: "Iron Maiden", year: 1982 },
  { title: "The Trooper", artist: "Iron Maiden", year: 1983 },
  { title: "Fear of the Dark", artist: "Iron Maiden", year: 1992 },
  { title: "Hallowed Be Thy Name", artist: "Iron Maiden", year: 1982 },
  { title: "The Number of the Beast", artist: "Iron Maiden", year: 1982 },
  { title: "Aces High", artist: "Iron Maiden", year: 1984 },
  { title: "Wasted Years", artist: "Iron Maiden", year: 1986 },
  { title: "Powerslave", artist: "Iron Maiden", year: 1984 },
  { title: "Breaking the Law", artist: "Judas Priest", year: 1980 },
  { title: "Living After Midnight", artist: "Judas Priest", year: 1980 },
  { title: "Painkiller", artist: "Judas Priest", year: 1990 },
  { title: "You've Got Another Thing Comin'", artist: "Judas Priest", year: 1982 },
  { title: "Hell Bent for Leather", artist: "Judas Priest", year: 1978 },

  // ── Journey / Foreigner / REO / Heart / Pat Benatar / Joan Jett ───────────
  { title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { title: "Any Way You Want It", artist: "Journey", year: 1980 },
  { title: "Faithfully", artist: "Journey", year: 1983 },
  { title: "Open Arms", artist: "Journey", year: 1981 },
  { title: "Separate Ways (Worlds Apart)", artist: "Journey", year: 1983 },
  { title: "Wheel in the Sky", artist: "Journey", year: 1978 },
  { title: "I Want to Know What Love Is", artist: "Foreigner", year: 1984 },
  { title: "Feels Like the First Time", artist: "Foreigner", year: 1977 },
  { title: "Cold as Ice", artist: "Foreigner", year: 1977 },
  { title: "Juke Box Hero", artist: "Foreigner", year: 1981 },
  { title: "Hot Blooded", artist: "Foreigner", year: 1978 },
  { title: "Waiting for a Girl Like You", artist: "Foreigner", year: 1981 },
  { title: "Keep on Loving You", artist: "REO Speedwagon", year: 1980 },
  { title: "Can't Fight This Feeling", artist: "REO Speedwagon", year: 1984 },
  { title: "Take It on the Run", artist: "REO Speedwagon", year: 1981 },
  { title: "Barracuda", artist: "Heart", year: 1977 },
  { title: "Alone", artist: "Heart", year: 1987 },
  { title: "Magic Man", artist: "Heart", year: 1975 },
  { title: "Crazy on You", artist: "Heart", year: 1975 },
  { title: "What About Love", artist: "Heart", year: 1985 },
  { title: "These Dreams", artist: "Heart", year: 1985 },
  { title: "Hit Me with Your Best Shot", artist: "Pat Benatar", year: 1980 },
  { title: "Love Is a Battlefield", artist: "Pat Benatar", year: 1983 },
  { title: "Heartbreaker", artist: "Pat Benatar", year: 1979 },
  { title: "We Belong", artist: "Pat Benatar", year: 1984 },
  { title: "Invincible", artist: "Pat Benatar", year: 1985 },
  { title: "I Love Rock 'n Roll", artist: "Joan Jett & the Blackhearts", year: 1982 },
  { title: "Bad Reputation", artist: "Joan Jett", year: 1980 },
  { title: "Crimson and Clover", artist: "Joan Jett & the Blackhearts", year: 1981 },

  // ── Scorpions / Twisted Sister / Whitesnake / Quiet Riot / Poison / Cinderella
  { title: "Wind of Change", artist: "Scorpions", year: 1990 },
  { title: "Rock You Like a Hurricane", artist: "Scorpions", year: 1984 },
  { title: "Still Loving You", artist: "Scorpions", year: 1984 },
  { title: "No One Like You", artist: "Scorpions", year: 1982 },
  { title: "We're Not Gonna Take It", artist: "Twisted Sister", year: 1984 },
  { title: "I Wanna Rock", artist: "Twisted Sister", year: 1984 },
  { title: "Here I Go Again", artist: "Whitesnake", year: 1987 },
  { title: "Is This Love", artist: "Whitesnake", year: 1987 },
  { title: "Still of the Night", artist: "Whitesnake", year: 1987 },
  { title: "Cum On Feel the Noize", artist: "Quiet Riot", year: 1983 },
  { title: "Every Rose Has Its Thorn", artist: "Poison", year: 1988 },
  { title: "Talk Dirty to Me", artist: "Poison", year: 1987 },
  { title: "Don't Know What You Got (Till It's Gone)", artist: "Cinderella", year: 1988 },

  // ── Nirvana ───────────────────────────────────────────────────────────────
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "Come as You Are", artist: "Nirvana", year: 1991 },
  { title: "Lithium", artist: "Nirvana", year: 1991 },
  { title: "In Bloom", artist: "Nirvana", year: 1991 },
  { title: "Heart-Shaped Box", artist: "Nirvana", year: 1993 },
  { title: "About a Girl", artist: "Nirvana", year: 1989 },
  { title: "All Apologies", artist: "Nirvana", year: 1993 },
  { title: "The Man Who Sold the World", artist: "Nirvana", year: 1994 },
  { title: "Polly", artist: "Nirvana", year: 1991 },
  { title: "Rape Me", artist: "Nirvana", year: 1993 },

  // ── Pearl Jam / Soundgarden / Alice in Chains / STP ───────────────────────
  { title: "Jeremy", artist: "Pearl Jam", year: 1992 },
  { title: "Alive", artist: "Pearl Jam", year: 1991 },
  { title: "Black", artist: "Pearl Jam", year: 1991 },
  { title: "Even Flow", artist: "Pearl Jam", year: 1991 },
  { title: "Yellow Ledbetter", artist: "Pearl Jam", year: 1992 },
  { title: "Better Man", artist: "Pearl Jam", year: 1994 },
  { title: "Daughter", artist: "Pearl Jam", year: 1993 },
  { title: "Last Kiss", artist: "Pearl Jam", year: 1999 },
  { title: "Animal", artist: "Pearl Jam", year: 1993 },
  { title: "Black Hole Sun", artist: "Soundgarden", year: 1994 },
  { title: "Spoonman", artist: "Soundgarden", year: 1994 },
  { title: "Fell on Black Days", artist: "Soundgarden", year: 1994 },
  { title: "Outshined", artist: "Soundgarden", year: 1991 },
  { title: "Rusty Cage", artist: "Soundgarden", year: 1991 },
  { title: "Burden in My Hand", artist: "Soundgarden", year: 1996 },
  { title: "Man in the Box", artist: "Alice in Chains", year: 1990 },
  { title: "Would?", artist: "Alice in Chains", year: 1992 },
  { title: "Rooster", artist: "Alice in Chains", year: 1992 },
  { title: "Down in a Hole", artist: "Alice in Chains", year: 1992 },
  { title: "Them Bones", artist: "Alice in Chains", year: 1992 },
  { title: "No Excuses", artist: "Alice in Chains", year: 1994 },
  { title: "Plush", artist: "Stone Temple Pilots", year: 1992 },
  { title: "Interstate Love Song", artist: "Stone Temple Pilots", year: 1994 },
  { title: "Vasoline", artist: "Stone Temple Pilots", year: 1994 },
  { title: "Sex Type Thing", artist: "Stone Temple Pilots", year: 1992 },
  { title: "Big Empty", artist: "Stone Temple Pilots", year: 1994 },
  { title: "Wicked Garden", artist: "Stone Temple Pilots", year: 1992 },

  // ── RHCP / Foo Fighters / Rage / Smashing Pumpkins ────────────────────────
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991 },
  { title: "Californication", artist: "Red Hot Chili Peppers", year: 1999 },
  { title: "Give It Away", artist: "Red Hot Chili Peppers", year: 1991 },
  { title: "Scar Tissue", artist: "Red Hot Chili Peppers", year: 1999 },
  { title: "Otherside", artist: "Red Hot Chili Peppers", year: 1999 },
  { title: "Snow (Hey Oh)", artist: "Red Hot Chili Peppers", year: 2006 },
  { title: "By the Way", artist: "Red Hot Chili Peppers", year: 2002 },
  { title: "Dani California", artist: "Red Hot Chili Peppers", year: 2006 },
  { title: "Can't Stop", artist: "Red Hot Chili Peppers", year: 2002 },
  { title: "Suck My Kiss", artist: "Red Hot Chili Peppers", year: 1991 },
  { title: "Soul to Squeeze", artist: "Red Hot Chili Peppers", year: 1993 },
  { title: "Everlong", artist: "Foo Fighters", year: 1997 },
  { title: "Learn to Fly", artist: "Foo Fighters", year: 1999 },
  { title: "Best of You", artist: "Foo Fighters", year: 2005 },
  { title: "The Pretender", artist: "Foo Fighters", year: 2007 },
  { title: "My Hero", artist: "Foo Fighters", year: 1997 },
  { title: "Times Like These", artist: "Foo Fighters", year: 2003 },
  { title: "All My Life", artist: "Foo Fighters", year: 2002 },
  { title: "Walk", artist: "Foo Fighters", year: 2011 },
  { title: "These Days", artist: "Foo Fighters", year: 2011 },
  { title: "Monkey Wrench", artist: "Foo Fighters", year: 1997 },
  { title: "Big Me", artist: "Foo Fighters", year: 1995 },
  { title: "Killing in the Name", artist: "Rage Against the Machine", year: 1992 },
  { title: "Bulls on Parade", artist: "Rage Against the Machine", year: 1996 },
  { title: "Guerrilla Radio", artist: "Rage Against the Machine", year: 1999 },
  { title: "Wake Up", artist: "Rage Against the Machine", year: 1992 },
  { title: "Sleep Now in the Fire", artist: "Rage Against the Machine", year: 1999 },
  { title: "1979", artist: "The Smashing Pumpkins", year: 1995 },
  { title: "Tonight, Tonight", artist: "The Smashing Pumpkins", year: 1995 },
  { title: "Bullet with Butterfly Wings", artist: "The Smashing Pumpkins", year: 1995 },
  { title: "Today", artist: "The Smashing Pumpkins", year: 1993 },
  { title: "Disarm", artist: "The Smashing Pumpkins", year: 1993 },
  { title: "Cherub Rock", artist: "The Smashing Pumpkins", year: 1993 },
  { title: "Zero", artist: "The Smashing Pumpkins", year: 1995 },

  // ── Radiohead / R.E.M. / Oasis / Blur ─────────────────────────────────────
  { title: "Creep", artist: "Radiohead", year: 1992 },
  { title: "Karma Police", artist: "Radiohead", year: 1997 },
  { title: "Paranoid Android", artist: "Radiohead", year: 1997 },
  { title: "No Surprises", artist: "Radiohead", year: 1997 },
  { title: "Just", artist: "Radiohead", year: 1995 },
  { title: "High and Dry", artist: "Radiohead", year: 1995 },
  { title: "Fake Plastic Trees", artist: "Radiohead", year: 1995 },
  { title: "Idioteque", artist: "Radiohead", year: 2000 },
  { title: "Lucky", artist: "Radiohead", year: 1997 },
  { title: "There There", artist: "Radiohead", year: 2003 },
  { title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { title: "Everybody Hurts", artist: "R.E.M.", year: 1992 },
  { title: "Man on the Moon", artist: "R.E.M.", year: 1992 },
  { title: "The One I Love", artist: "R.E.M.", year: 1987 },
  { title: "Stand", artist: "R.E.M.", year: 1988 },
  { title: "Shiny Happy People", artist: "R.E.M.", year: 1991 },
  { title: "It's the End of the World as We Know It (And I Feel Fine)", artist: "R.E.M.", year: 1987 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "Don't Look Back in Anger", artist: "Oasis", year: 1996 },
  { title: "Champagne Supernova", artist: "Oasis", year: 1995 },
  { title: "Live Forever", artist: "Oasis", year: 1994 },
  { title: "Some Might Say", artist: "Oasis", year: 1995 },
  { title: "Roll with It", artist: "Oasis", year: 1995 },
  { title: "Morning Glory", artist: "Oasis", year: 1995 },
  { title: "Supersonic", artist: "Oasis", year: 1994 },
  { title: "Song 2", artist: "Blur", year: 1997 },
  { title: "Girls & Boys", artist: "Blur", year: 1994 },
  { title: "Parklife", artist: "Blur", year: 1994 },
  { title: "Coffee & TV", artist: "Blur", year: 1999 },
  { title: "Country House", artist: "Blur", year: 1995 },

  // ── Green Day / Weezer / No Doubt / Cranberries / Live / Bush / Garbage ───
  { title: "Basket Case", artist: "Green Day", year: 1994 },
  { title: "Good Riddance (Time of Your Life)", artist: "Green Day", year: 1997 },
  { title: "When I Come Around", artist: "Green Day", year: 1994 },
  { title: "Longview", artist: "Green Day", year: 1994 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
  { title: "American Idiot", artist: "Green Day", year: 2004 },
  { title: "Holiday", artist: "Green Day", year: 2004 },
  { title: "Wake Me Up When September Ends", artist: "Green Day", year: 2004 },
  { title: "21 Guns", artist: "Green Day", year: 2009 },
  { title: "Brain Stew", artist: "Green Day", year: 1995 },
  { title: "Welcome to Paradise", artist: "Green Day", year: 1994 },
  { title: "Buddy Holly", artist: "Weezer", year: 1994 },
  { title: "Say It Ain't So", artist: "Weezer", year: 1995 },
  { title: "Undone (The Sweater Song)", artist: "Weezer", year: 1994 },
  { title: "Beverly Hills", artist: "Weezer", year: 2005 },
  { title: "Island in the Sun", artist: "Weezer", year: 2001 },
  { title: "Hash Pipe", artist: "Weezer", year: 2001 },
  { title: "My Name Is Jonas", artist: "Weezer", year: 1994 },
  { title: "Just a Girl", artist: "No Doubt", year: 1995 },
  { title: "Don't Speak", artist: "No Doubt", year: 1996 },
  { title: "Spiderwebs", artist: "No Doubt", year: 1995 },
  { title: "Hey Baby", artist: "No Doubt", year: 2001 },
  { title: "Zombie", artist: "The Cranberries", year: 1994 },
  { title: "Linger", artist: "The Cranberries", year: 1993 },
  { title: "Dreams", artist: "The Cranberries", year: 1992 },
  { title: "Lightning Crashes", artist: "Live", year: 1994 },
  { title: "I Alone", artist: "Live", year: 1994 },
  { title: "Glycerine", artist: "Bush", year: 1994 },
  { title: "Machinehead", artist: "Bush", year: 1994 },
  { title: "Everything Zen", artist: "Bush", year: 1994 },
  { title: "Stupid Girl", artist: "Garbage", year: 1995 },
  { title: "Only Happy When It Rains", artist: "Garbage", year: 1995 },
  { title: "#1 Crush", artist: "Garbage", year: 1996 },
  { title: "What I Got", artist: "Sublime", year: 1996 },
  { title: "Santeria", artist: "Sublime", year: 1996 },
  { title: "Wrong Way", artist: "Sublime", year: 1996 },
  { title: "Self Esteem", artist: "The Offspring", year: 1994 },
  { title: "Come Out and Play", artist: "The Offspring", year: 1994 },
  { title: "Pretty Fly (For a White Guy)", artist: "The Offspring", year: 1998 },
  { title: "Why Don't You Get a Job?", artist: "The Offspring", year: 1998 },
  { title: "All the Small Things", artist: "Blink-182", year: 1999 },
  { title: "What's My Age Again?", artist: "Blink-182", year: 1999 },
  { title: "Adam's Song", artist: "Blink-182", year: 1999 },
  { title: "Dammit", artist: "Blink-182", year: 1997 },
  { title: "First Date", artist: "Blink-182", year: 2001 },
  { title: "I Miss You", artist: "Blink-182", year: 2003 },

  // ── Metallica ─────────────────────────────────────────────────────────────
  { title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { title: "Nothing Else Matters", artist: "Metallica", year: 1991 },
  { title: "One", artist: "Metallica", year: 1988 },
  { title: "Master of Puppets", artist: "Metallica", year: 1986 },
  { title: "Fade to Black", artist: "Metallica", year: 1984 },
  { title: "Sad but True", artist: "Metallica", year: 1991 },
  { title: "The Unforgiven", artist: "Metallica", year: 1991 },
  { title: "Battery", artist: "Metallica", year: 1986 },
  { title: "Seek & Destroy", artist: "Metallica", year: 1983 },
  { title: "For Whom the Bell Tolls", artist: "Metallica", year: 1984 },
  { title: "Wherever I May Roam", artist: "Metallica", year: 1991 },
  { title: "Welcome Home (Sanitarium)", artist: "Metallica", year: 1986 },

  // ── 2000s rock ────────────────────────────────────────────────────────────
  { title: "Seven Nation Army", artist: "The White Stripes", year: 2003 },
  { title: "Fell in Love with a Girl", artist: "The White Stripes", year: 2001 },
  { title: "Icky Thump", artist: "The White Stripes", year: 2007 },
  { title: "Blue Orchid", artist: "The White Stripes", year: 2005 },
  { title: "Last Nite", artist: "The Strokes", year: 2001 },
  { title: "Reptilia", artist: "The Strokes", year: 2003 },
  { title: "Someday", artist: "The Strokes", year: 2001 },
  { title: "You Only Live Once", artist: "The Strokes", year: 2006 },
  { title: "Hard to Explain", artist: "The Strokes", year: 2001 },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { title: "Somebody Told Me", artist: "The Killers", year: 2004 },
  { title: "When You Were Young", artist: "The Killers", year: 2006 },
  { title: "Human", artist: "The Killers", year: 2008 },
  { title: "Read My Mind", artist: "The Killers", year: 2006 },
  { title: "All These Things That I've Done", artist: "The Killers", year: 2004 },
  { title: "I Bet You Look Good on the Dancefloor", artist: "Arctic Monkeys", year: 2005 },
  { title: "Do I Wanna Know?", artist: "Arctic Monkeys", year: 2013 },
  { title: "R U Mine?", artist: "Arctic Monkeys", year: 2012 },
  { title: "Fluorescent Adolescent", artist: "Arctic Monkeys", year: 2007 },
  { title: "505", artist: "Arctic Monkeys", year: 2007 },
  { title: "Why'd You Only Call Me When You're High?", artist: "Arctic Monkeys", year: 2013 },
  { title: "Supermassive Black Hole", artist: "Muse", year: 2006 },
  { title: "Uprising", artist: "Muse", year: 2009 },
  { title: "Time Is Running Out", artist: "Muse", year: 2003 },
  { title: "Knights of Cydonia", artist: "Muse", year: 2006 },
  { title: "Plug In Baby", artist: "Muse", year: 2001 },
  { title: "Starlight", artist: "Muse", year: 2006 },
  { title: "Hysteria", artist: "Muse", year: 2003 },
  { title: "Madness", artist: "Muse", year: 2012 },
  { title: "Use Somebody", artist: "Kings of Leon", year: 2008 },
  { title: "Sex on Fire", artist: "Kings of Leon", year: 2008 },
  { title: "Closer", artist: "Kings of Leon", year: 2008 },
  { title: "On Call", artist: "Kings of Leon", year: 2007 },
  { title: "Yellow", artist: "Coldplay", year: 2000 },
  { title: "The Scientist", artist: "Coldplay", year: 2002 },
  { title: "Clocks", artist: "Coldplay", year: 2002 },
  { title: "Fix You", artist: "Coldplay", year: 2005 },
  { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { title: "Speed of Sound", artist: "Coldplay", year: 2005 },
  { title: "In My Place", artist: "Coldplay", year: 2002 },
  { title: "Trouble", artist: "Coldplay", year: 2000 },
  { title: "A Sky Full of Stars", artist: "Coldplay", year: 2014 },
  { title: "In the End", artist: "Linkin Park", year: 2001 },
  { title: "Numb", artist: "Linkin Park", year: 2003 },
  { title: "Crawling", artist: "Linkin Park", year: 2001 },
  { title: "What I've Done", artist: "Linkin Park", year: 2007 },
  { title: "Somewhere I Belong", artist: "Linkin Park", year: 2003 },
  { title: "Breaking the Habit", artist: "Linkin Park", year: 2003 },
  { title: "Faint", artist: "Linkin Park", year: 2003 },
  { title: "Lying from You", artist: "Linkin Park", year: 2003 },
  { title: "Bleed It Out", artist: "Linkin Park", year: 2007 },
  { title: "Chop Suey!", artist: "System of a Down", year: 2001 },
  { title: "Toxicity", artist: "System of a Down", year: 2001 },
  { title: "B.Y.O.B.", artist: "System of a Down", year: 2005 },
  { title: "Aerials", artist: "System of a Down", year: 2001 },
  { title: "Hypnotize", artist: "System of a Down", year: 2005 },
  { title: "How You Remind Me", artist: "Nickelback", year: 2001 },
  { title: "Photograph", artist: "Nickelback", year: 2005 },
  { title: "Rockstar", artist: "Nickelback", year: 2005 },
  { title: "Far Away", artist: "Nickelback", year: 2005 },
  { title: "Kryptonite", artist: "3 Doors Down", year: 2000 },
  { title: "Here Without You", artist: "3 Doors Down", year: 2003 },
  { title: "When I'm Gone", artist: "3 Doors Down", year: 2002 },
  { title: "Like a Stone", artist: "Audioslave", year: 2002 },
  { title: "Be Yourself", artist: "Audioslave", year: 2005 },
  { title: "Cochise", artist: "Audioslave", year: 2002 },
  { title: "Slither", artist: "Velvet Revolver", year: 2004 },
  { title: "Fall to Pieces", artist: "Velvet Revolver", year: 2004 },
  { title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006 },
  { title: "Helena", artist: "My Chemical Romance", year: 2004 },
  { title: "Teenagers", artist: "My Chemical Romance", year: 2006 },
  { title: "I'm Not Okay (I Promise)", artist: "My Chemical Romance", year: 2004 },
  { title: "Famous Last Words", artist: "My Chemical Romance", year: 2006 },
  { title: "Sugar, We're Goin Down", artist: "Fall Out Boy", year: 2005 },
  { title: "Thnks fr th Mmrs", artist: "Fall Out Boy", year: 2007 },
  { title: "Dance, Dance", artist: "Fall Out Boy", year: 2005 },
  { title: "Centuries", artist: "Fall Out Boy", year: 2014 },
  { title: "Immortals", artist: "Fall Out Boy", year: 2014 },
  { title: "Misery Business", artist: "Paramore", year: 2007 },
  { title: "Decode", artist: "Paramore", year: 2008 },
  { title: "Ain't It Fun", artist: "Paramore", year: 2013 },
  { title: "Still Into You", artist: "Paramore", year: 2013 },
  { title: "The Only Exception", artist: "Paramore", year: 2009 },
  { title: "I Write Sins Not Tragedies", artist: "Panic! at the Disco", year: 2005 },
  { title: "High Hopes", artist: "Panic! at the Disco", year: 2018 },
  { title: "Death of a Bachelor", artist: "Panic! at the Disco", year: 2016 },
  { title: "This Is Gospel", artist: "Panic! at the Disco", year: 2013 },
  { title: "Bring Me to Life", artist: "Evanescence", year: 2003 },
  { title: "My Immortal", artist: "Evanescence", year: 2003 },
  { title: "Going Under", artist: "Evanescence", year: 2003 },

  // ── 2010s+ rock ───────────────────────────────────────────────────────────
  { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
  { title: "Demons", artist: "Imagine Dragons", year: 2012 },
  { title: "Believer", artist: "Imagine Dragons", year: 2017 },
  { title: "Thunder", artist: "Imagine Dragons", year: 2017 },
  { title: "Whatever It Takes", artist: "Imagine Dragons", year: 2017 },
  { title: "Bad Liar", artist: "Imagine Dragons", year: 2018 },
  { title: "Natural", artist: "Imagine Dragons", year: 2018 },
  { title: "Stressed Out", artist: "Twenty One Pilots", year: 2015 },
  { title: "Heathens", artist: "Twenty One Pilots", year: 2016 },
  { title: "Ride", artist: "Twenty One Pilots", year: 2015 },
  { title: "Car Radio", artist: "Twenty One Pilots", year: 2013 },
  { title: "Tear in My Heart", artist: "Twenty One Pilots", year: 2015 },
  { title: "Little Lion Man", artist: "Mumford & Sons", year: 2009 },
  { title: "I Will Wait", artist: "Mumford & Sons", year: 2012 },
  { title: "The Cave", artist: "Mumford & Sons", year: 2010 },
  { title: "Believe", artist: "Mumford & Sons", year: 2015 },
  { title: "Lonely Boy", artist: "The Black Keys", year: 2011 },
  { title: "Tighten Up", artist: "The Black Keys", year: 2010 },
  { title: "Howlin' for You", artist: "The Black Keys", year: 2010 },
  { title: "Gold on the Ceiling", artist: "The Black Keys", year: 2011 },
  { title: "Fever", artist: "The Black Keys", year: 2014 },
  { title: "A-Punk", artist: "Vampire Weekend", year: 2008 },
  { title: "Cousins", artist: "Vampire Weekend", year: 2009 },
  { title: "Oxford Comma", artist: "Vampire Weekend", year: 2008 },
  { title: "Step", artist: "Vampire Weekend", year: 2013 },
  { title: "Wake Up", artist: "Arcade Fire", year: 2004 },
  { title: "Reflektor", artist: "Arcade Fire", year: 2013 },
  { title: "Ready to Start", artist: "Arcade Fire", year: 2010 },
  { title: "The Suburbs", artist: "Arcade Fire", year: 2010 },
  { title: "The Less I Know the Better", artist: "Tame Impala", year: 2015 },
  { title: "Let It Happen", artist: "Tame Impala", year: 2015 },
  { title: "Feels Like We Only Go Backwards", artist: "Tame Impala", year: 2012 },
  { title: "Ain't No Rest for the Wicked", artist: "Cage the Elephant", year: 2008 },
  { title: "Shake Me Down", artist: "Cage the Elephant", year: 2011 },
  { title: "Cigarette Daydreams", artist: "Cage the Elephant", year: 2013 },
  { title: "Take Me to Church", artist: "Hozier", year: 2013 },
  { title: "Work Song", artist: "Hozier", year: 2014 },
  { title: "Ho Hey", artist: "The Lumineers", year: 2012 },
  { title: "Ophelia", artist: "The Lumineers", year: 2016 },
  { title: "Cleopatra", artist: "The Lumineers", year: 2016 },
  { title: "Little Talks", artist: "Of Monsters and Men", year: 2011 },
  { title: "Mountain Sound", artist: "Of Monsters and Men", year: 2012 },
  { title: "Skinny Love", artist: "Bon Iver", year: 2007 },

  // ── Tom Petty / Springsteen / Seger / Steve Miller / ZZ Top / Dire Straits / Fleetwood Mac ──
  { title: "Free Fallin'", artist: "Tom Petty", year: 1989 },
  { title: "I Won't Back Down", artist: "Tom Petty", year: 1989 },
  { title: "American Girl", artist: "Tom Petty", year: 1976 },
  { title: "Runnin' Down a Dream", artist: "Tom Petty", year: 1989 },
  { title: "Learning to Fly", artist: "Tom Petty", year: 1991 },
  { title: "You Don't Know How It Feels", artist: "Tom Petty", year: 1994 },
  { title: "Mary Jane's Last Dance", artist: "Tom Petty", year: 1993 },
  { title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
  { title: "Born in the U.S.A.", artist: "Bruce Springsteen", year: 1984 },
  { title: "Dancing in the Dark", artist: "Bruce Springsteen", year: 1984 },
  { title: "Glory Days", artist: "Bruce Springsteen", year: 1984 },
  { title: "Thunder Road", artist: "Bruce Springsteen", year: 1975 },
  { title: "The River", artist: "Bruce Springsteen", year: 1980 },
  { title: "Streets of Philadelphia", artist: "Bruce Springsteen", year: 1994 },
  { title: "Old Time Rock and Roll", artist: "Bob Seger", year: 1978 },
  { title: "Night Moves", artist: "Bob Seger", year: 1976 },
  { title: "Against the Wind", artist: "Bob Seger", year: 1980 },
  { title: "Turn the Page", artist: "Bob Seger", year: 1973 },
  { title: "The Joker", artist: "Steve Miller Band", year: 1973 },
  { title: "Fly Like an Eagle", artist: "Steve Miller Band", year: 1976 },
  { title: "Rock'n Me", artist: "Steve Miller Band", year: 1976 },
  { title: "Take the Money and Run", artist: "Steve Miller Band", year: 1976 },
  { title: "Sharp Dressed Man", artist: "ZZ Top", year: 1983 },
  { title: "Legs", artist: "ZZ Top", year: 1983 },
  { title: "La Grange", artist: "ZZ Top", year: 1973 },
  { title: "Gimme All Your Lovin'", artist: "ZZ Top", year: 1983 },
  { title: "Sultans of Swing", artist: "Dire Straits", year: 1978 },
  { title: "Money for Nothing", artist: "Dire Straits", year: 1985 },
  { title: "Walk of Life", artist: "Dire Straits", year: 1985 },
  { title: "Romeo and Juliet", artist: "Dire Straits", year: 1980 },
  { title: "Brothers in Arms", artist: "Dire Straits", year: 1985 },
  { title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977 },
  { title: "Dreams", artist: "Fleetwood Mac", year: 1977 },
  { title: "The Chain", artist: "Fleetwood Mac", year: 1977 },
  { title: "Landslide", artist: "Fleetwood Mac", year: 1975 },
  { title: "Rhiannon", artist: "Fleetwood Mac", year: 1975 },
  { title: "Don't Stop", artist: "Fleetwood Mac", year: 1977 },
  { title: "Gold Dust Woman", artist: "Fleetwood Mac", year: 1977 },
  { title: "Tusk", artist: "Fleetwood Mac", year: 1979 },

  // ── Bowie / Elton John / U2 / Talking Heads / The Cure / Clash / Pistols / Ramones ──
  { title: "Heroes", artist: "David Bowie", year: 1977 },
  { title: "Space Oddity", artist: "David Bowie", year: 1969 },
  { title: "Ziggy Stardust", artist: "David Bowie", year: 1972 },
  { title: "Rebel Rebel", artist: "David Bowie", year: 1974 },
  { title: "Suffragette City", artist: "David Bowie", year: 1972 },
  { title: "Let's Dance", artist: "David Bowie", year: 1983 },
  { title: "Modern Love", artist: "David Bowie", year: 1983 },
  { title: "Rocket Man", artist: "Elton John", year: 1972 },
  { title: "Tiny Dancer", artist: "Elton John", year: 1971 },
  { title: "Crocodile Rock", artist: "Elton John", year: 1972 },
  { title: "Saturday Night's Alright for Fighting", artist: "Elton John", year: 1973 },
  { title: "Bennie and the Jets", artist: "Elton John", year: 1973 },
  { title: "One", artist: "U2", year: 1991 },
  { title: "With or Without You", artist: "U2", year: 1987 },
  { title: "Where the Streets Have No Name", artist: "U2", year: 1987 },
  { title: "Beautiful Day", artist: "U2", year: 2000 },
  { title: "Sunday Bloody Sunday", artist: "U2", year: 1983 },
  { title: "I Still Haven't Found What I'm Looking For", artist: "U2", year: 1987 },
  { title: "Pride (In the Name of Love)", artist: "U2", year: 1984 },
  { title: "Vertigo", artist: "U2", year: 2004 },
  { title: "Elevation", artist: "U2", year: 2000 },
  { title: "Once in a Lifetime", artist: "Talking Heads", year: 1980 },
  { title: "Psycho Killer", artist: "Talking Heads", year: 1977 },
  { title: "Burning Down the House", artist: "Talking Heads", year: 1983 },
  { title: "Take Me to the River", artist: "Talking Heads", year: 1978 },
  { title: "Friday I'm in Love", artist: "The Cure", year: 1992 },
  { title: "Boys Don't Cry", artist: "The Cure", year: 1979 },
  { title: "Lovesong", artist: "The Cure", year: 1989 },
  { title: "Just Like Heaven", artist: "The Cure", year: 1987 },
  { title: "Pictures of You", artist: "The Cure", year: 1989 },
  { title: "London Calling", artist: "The Clash", year: 1979 },
  { title: "Should I Stay or Should I Go", artist: "The Clash", year: 1982 },
  { title: "Rock the Casbah", artist: "The Clash", year: 1982 },
  { title: "Train in Vain", artist: "The Clash", year: 1979 },
  { title: "Anarchy in the U.K.", artist: "Sex Pistols", year: 1976 },
  { title: "God Save the Queen", artist: "Sex Pistols", year: 1977 },
  { title: "Blitzkrieg Bop", artist: "Ramones", year: 1976 },
  { title: "I Wanna Be Sedated", artist: "Ramones", year: 1978 },
  { title: "Sheena Is a Punk Rocker", artist: "Ramones", year: 1977 },
];

module.exports = SONGS3;
