// Curated list of well-known songs spanning all decades
// The server will search Spotify for these by title + artist to get real track IDs + preview URLs

const SONGS = [
  // 1950s
  { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958 },
  { title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
  { title: "Great Balls of Fire", artist: "Jerry Lee Lewis", year: 1957 },
  { title: "Tutti Frutti", artist: "Little Richard", year: 1955 },
  { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
  { title: "Blue Suede Shoes", artist: "Elvis Presley", year: 1956 },
  { title: "Maybellene", artist: "Chuck Berry", year: 1955 },
  { title: "Ring of Fire", artist: "Johnny Cash", year: 1963 },
  { title: "I Walk the Line", artist: "Johnny Cash", year: 1956 },

  // 1960s
  { title: "Hey Jude", artist: "The Beatles", year: 1968 },
  { title: "Let It Be", artist: "The Beatles", year: 1970 },
  { title: "Yesterday", artist: "The Beatles", year: 1965 },
  { title: "Come Together", artist: "The Beatles", year: 1969 },
  { title: "Twist and Shout", artist: "The Beatles", year: 1963 },
  { title: "Help!", artist: "The Beatles", year: 1965 },
  { title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { title: "Natural Woman", artist: "Aretha Franklin", year: 1967 },
  { title: "Purple Haze", artist: "Jimi Hendrix", year: 1967 },
  { title: "All Along the Watchtower", artist: "Jimi Hendrix", year: 1968 },
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
  { title: "Sympathy for the Devil", artist: "The Rolling Stones", year: 1968 },
  { title: "Jumpin' Jack Flash", artist: "The Rolling Stones", year: 1968 },
  { title: "What's Going On", artist: "Marvin Gaye", year: 1971 },
  { title: "Like a Rolling Stone", artist: "Bob Dylan", year: 1965 },
  { title: "The Sound of Silence", artist: "Simon & Garfunkel", year: 1965 },
  { title: "Mrs. Robinson", artist: "Simon & Garfunkel", year: 1968 },
  { title: "My Generation", artist: "The Who", year: 1965 },
  { title: "Pinball Wizard", artist: "The Who", year: 1969 },
  { title: "Evil Ways", artist: "Santana", year: 1969 },
  { title: "Your Song", artist: "Elton John", year: 1970 },

  // 1970s
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "We Will Rock You", artist: "Queen", year: 1977 },
  { title: "We Are the Champions", artist: "Queen", year: 1977 },
  { title: "Don't Stop Me Now", artist: "Queen", year: 1978 },
  { title: "Somebody to Love", artist: "Queen", year: 1976 },
  { title: "Killer Queen", artist: "Queen", year: 1974 },
  { title: "Hotel California", artist: "Eagles", year: 1977 },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
  { title: "Whole Lotta Love", artist: "Led Zeppelin", year: 1969 },
  { title: "Kashmir", artist: "Led Zeppelin", year: 1975 },
  { title: "Black Dog", artist: "Led Zeppelin", year: 1971 },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { title: "How Deep Is Your Love", artist: "Bee Gees", year: 1977 },
  { title: "Born to Run", artist: "Bruce Springsteen", year: 1975 },
  { title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977 },
  { title: "Dancing Queen", artist: "ABBA", year: 1976 },
  { title: "Mamma Mia", artist: "ABBA", year: 1975 },
  { title: "Fernando", artist: "ABBA", year: 1976 },
  { title: "Waterloo", artist: "ABBA", year: 1974 },
  { title: "September", artist: "Earth, Wind & Fire", year: 1978 },
  { title: "Dreams", artist: "Fleetwood Mac", year: 1977 },
  { title: "Le Freak", artist: "Chic", year: 1978 },
  { title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
  { title: "Superstition", artist: "Stevie Wonder", year: 1972 },
  { title: "Sir Duke", artist: "Stevie Wonder", year: 1977 },
  { title: "Isn't She Lovely", artist: "Stevie Wonder", year: 1976 },
  { title: "Heroes", artist: "David Bowie", year: 1977 },
  { title: "Space Oddity", artist: "David Bowie", year: 1969 },
  { title: "Life on Mars", artist: "David Bowie", year: 1971 },
  { title: "Changes", artist: "David Bowie", year: 1971 },
  { title: "Ziggy Stardust", artist: "David Bowie", year: 1972 },
  { title: "Rocket Man", artist: "Elton John", year: 1972 },
  { title: "Tiny Dancer", artist: "Elton John", year: 1971 },
  { title: "Crocodile Rock", artist: "Elton John", year: 1972 },
  { title: "Don't Let the Sun Go Down on Me", artist: "Elton John", year: 1974 },
  { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", year: 1970 },
  { title: "Heart of Gold", artist: "Neil Young", year: 1972 },
  { title: "Old Man", artist: "Neil Young", year: 1972 },
  { title: "Baba O'Riley", artist: "The Who", year: 1971 },
  { title: "Won't Get Fooled Again", artist: "The Who", year: 1971 },
  { title: "Sultans of Swing", artist: "Dire Straits", year: 1978 },
  { title: "No Woman No Cry", artist: "Bob Marley", year: 1975 },
  { title: "Redemption Song", artist: "Bob Marley", year: 1980 },
  { title: "One Love", artist: "Bob Marley", year: 1977 },
  { title: "Jamming", artist: "Bob Marley", year: 1977 },
  { title: "Is This Love", artist: "Bob Marley", year: 1978 },
  { title: "Oye Como Va", artist: "Santana", year: 1970 },
  { title: "Black Magic Woman", artist: "Santana", year: 1970 },
  { title: "Europa", artist: "Santana", year: 1976 },
  { title: "Wish You Were Here", artist: "Pink Floyd", year: 1975 },
  { title: "Comfortably Numb", artist: "Pink Floyd", year: 1979 },
  { title: "Another Brick in the Wall", artist: "Pink Floyd", year: 1979 },
  { title: "Money", artist: "Pink Floyd", year: 1973 },
  { title: "Time", artist: "Pink Floyd", year: 1973 },
  { title: "Shine On You Crazy Diamond", artist: "Pink Floyd", year: 1975 },
  { title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { title: "Dream On", artist: "Aerosmith", year: 1973 },
  { title: "Walk This Way", artist: "Aerosmith", year: 1975 },
  { title: "Jolene", artist: "Dolly Parton", year: 1973 },
  { title: "50 Ways to Leave Your Lover", artist: "Paul Simon", year: 1975 },
  { title: "Fame", artist: "David Bowie", year: 1975 },

  // 1980s
  { title: "Billie Jean", artist: "Michael Jackson", year: 1982 },
  { title: "Thriller", artist: "Michael Jackson", year: 1982 },
  { title: "Beat It", artist: "Michael Jackson", year: 1982 },
  { title: "Man in the Mirror", artist: "Michael Jackson", year: 1988 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "November Rain", artist: "Guns N' Roses", year: 1991 },
  { title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { title: "Like a Virgin", artist: "Madonna", year: 1984 },
  { title: "Material Girl", artist: "Madonna", year: 1984 },
  { title: "Like a Prayer", artist: "Madonna", year: 1989 },
  { title: "Take On Me", artist: "a-ha", year: 1985 },
  { title: "Eye of the Tiger", artist: "Survivor", year: 1982 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "You Give Love a Bad Name", artist: "Bon Jovi", year: 1986 },
  { title: "Wanted Dead or Alive", artist: "Bon Jovi", year: 1986 },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { title: "Roxanne", artist: "The Police", year: 1978 },
  { title: "Message in a Bottle", artist: "The Police", year: 1979 },
  { title: "When Doves Cry", artist: "Prince", year: 1984 },
  { title: "Purple Rain", artist: "Prince", year: 1984 },
  { title: "Kiss", artist: "Prince", year: 1986 },
  { title: "With or Without You", artist: "U2", year: 1987 },
  { title: "Where the Streets Have No Name", artist: "U2", year: 1987 },
  { title: "One", artist: "U2", year: 1991 },
  { title: "Don't You (Forget About Me)", artist: "Simple Minds", year: 1985 },
  { title: "Wake Me Up Before You Go-Go", artist: "Wham!", year: 1984 },
  { title: "Careless Whisper", artist: "George Michael", year: 1984 },
  { title: "Faith", artist: "George Michael", year: 1987 },
  { title: "Africa", artist: "Toto", year: 1982 },
  { title: "Jump", artist: "Van Halen", year: 1984 },
  { title: "Come On Eileen", artist: "Dexys Midnight Runners", year: 1982 },
  { title: "99 Luftballons", artist: "Nena", year: 1983 },
  { title: "Running Up That Hill", artist: "Kate Bush", year: 1985 },
  { title: "Wuthering Heights", artist: "Kate Bush", year: 1978 },
  { title: "Back in Black", artist: "AC/DC", year: 1980 },
  { title: "Thunderstruck", artist: "AC/DC", year: 1990 },
  { title: "Pour Some Sugar on Me", artist: "Def Leppard", year: 1987 },
  { title: "Money for Nothing", artist: "Dire Straits", year: 1985 },
  { title: "Walk of Life", artist: "Dire Straits", year: 1985 },
  { title: "Let's Dance", artist: "David Bowie", year: 1983 },
  { title: "China Girl", artist: "David Bowie", year: 1983 },
  { title: "I'm Still Standing", artist: "Elton John", year: 1983 },
  { title: "I Just Called to Say I Love You", artist: "Stevie Wonder", year: 1984 },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987 },
  { title: "Greatest Love of All", artist: "Whitney Houston", year: 1986 },
  { title: "9 to 5", artist: "Dolly Parton", year: 1980 },
  { title: "Under Pressure", artist: "Queen", year: 1981 },
  { title: "Radio Ga Ga", artist: "Queen", year: 1984 },
  { title: "Smooth Criminal", artist: "Michael Jackson", year: 1987 },
  { title: "Don't Stop (Thinking About Tomorrow)", artist: "Fleetwood Mac", year: 1977 },
  { title: "Crazy Little Thing Called Love", artist: "Queen", year: 1979 },
  { title: "You Can Call Me Al", artist: "Paul Simon", year: 1986 },
  { title: "Roam", artist: "B-52s", year: 1989 },
  { title: "Love Shack", artist: "B-52s", year: 1989 },

  // 1990s
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "Come as You Are", artist: "Nirvana", year: 1991 },
  { title: "Lithium", artist: "Nirvana", year: 1991 },
  { title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { title: "Everybody Hurts", artist: "R.E.M.", year: 1992 },
  { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
  { title: "Creep", artist: "Radiohead", year: 1992 },
  { title: "Fake Plastic Trees", artist: "Radiohead", year: 1995 },
  { title: "Jeremy", artist: "Pearl Jam", year: 1992 },
  { title: "Black Hole Sun", artist: "Soundgarden", year: 1994 },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1992 },
  { title: "Californication", artist: "Red Hot Chili Peppers", year: 1999 },
  { title: "Give It Away", artist: "Red Hot Chili Peppers", year: 1991 },
  { title: "Baby One More Time", artist: "Britney Spears", year: 1998 },
  { title: "Toxic", artist: "Britney Spears", year: 2004 },
  { title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { title: "2 Become 1", artist: "Spice Girls", year: 1996 },
  { title: "Waterfalls", artist: "TLC", year: 1995 },
  { title: "No Scrubs", artist: "TLC", year: 1999 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "Don't Look Back in Anger", artist: "Oasis", year: 1996 },
  { title: "Champagne Supernova", artist: "Oasis", year: 1995 },
  { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
  { title: "Think Twice", artist: "Celine Dion", year: 1994 },
  { title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
  { title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { title: "Nothing Else Matters", artist: "Metallica", year: 1991 },
  { title: "Killing Me Softly", artist: "Fugees", year: 1996 },
  { title: "Un-Break My Heart", artist: "Toni Braxton", year: 1996 },
  { title: "Iris", artist: "Goo Goo Dolls", year: 1998 },
  { title: "Say My Name", artist: "Destiny's Child", year: 1999 },
  { title: "Juicy", artist: "The Notorious B.I.G.", year: 1994 },
  { title: "Hypnotize", artist: "The Notorious B.I.G.", year: 1997 },
  { title: "California Love", artist: "2Pac", year: 1995 },
  { title: "Changes", artist: "2Pac", year: 1998 },
  { title: "Gin and Juice", artist: "Snoop Dogg", year: 1993 },
  { title: "What's My Age Again?", artist: "Blink-182", year: 1999 },
  { title: "All Star", artist: "Smash Mouth", year: 1999 },
  { title: "Smooth", artist: "Santana", year: 1999 },
  { title: "Corazon Espinado", artist: "Santana", year: 1999 },
  { title: "Man! I Feel Like a Woman", artist: "Shania Twain", year: 1999 },
  { title: "That Don't Impress Me Much", artist: "Shania Twain", year: 1998 },
  { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", year: 1998 },
  { title: "Livin' La Vida Loca", artist: "Ricky Martin", year: 1999 },
  { title: "Genie in a Bottle", artist: "Christina Aguilera", year: 1999 },
  { title: "Beautiful", artist: "Christina Aguilera", year: 2002 },
  { title: "Larger Than Life", artist: "Backstreet Boys", year: 1999 },
  { title: "Quit Playing Games", artist: "Backstreet Boys", year: 1996 },
  { title: "Tearin' Up My Heart", artist: "NSYNC", year: 1997 },
  { title: "Hurt", artist: "Johnny Cash", year: 2002 },
  { title: "Rockin' in the Free World", artist: "Neil Young", year: 1989 },
  { title: "Mr. Jones", artist: "Counting Crows", year: 1993 },
  { title: "Semi-Charmed Life", artist: "Third Eye Blind", year: 1997 },
  { title: "Torn", artist: "Natalie Imbruglia", year: 1997 },
  { title: "You Oughta Know", artist: "Alanis Morissette", year: 1995 },
  { title: "Ironic", artist: "Alanis Morissette", year: 1995 },
  { title: "Basket Case", artist: "Green Day", year: 1994 },
  { title: "When I Come Around", artist: "Green Day", year: 1994 },
  { title: "Zombie", artist: "The Cranberries", year: 1994 },
  { title: "Linger", artist: "The Cranberries", year: 1993 },

  // 2000s
  { title: "Lose Yourself", artist: "Eminem", year: 2002 },
  { title: "Without Me", artist: "Eminem", year: 2002 },
  { title: "In Da Club", artist: "50 Cent", year: 2003 },
  { title: "Yeah!", artist: "Usher", year: 2004 },
  { title: "Crazy in Love", artist: "Beyoncé", year: 2003 },
  { title: "Halo", artist: "Beyoncé", year: 2008 },
  { title: "Beautiful Day", artist: "U2", year: 2000 },
  { title: "Hey Ya!", artist: "Outkast", year: 2003 },
  { title: "Cry Me a River", artist: "Justin Timberlake", year: 2002 },
  { title: "SexyBack", artist: "Justin Timberlake", year: 2006 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
  { title: "Umbrella", artist: "Rihanna", year: 2007 },
  { title: "Pon de Replay", artist: "Rihanna", year: 2005 },
  { title: "We Found Love", artist: "Rihanna", year: 2011 },
  { title: "Love Story", artist: "Taylor Swift", year: 2008 },
  { title: "You Belong with Me", artist: "Taylor Swift", year: 2009 },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { title: "Just Dance", artist: "Lady Gaga", year: 2008 },
  { title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  { title: "Single Ladies", artist: "Beyoncé", year: 2008 },
  { title: "Hips Don't Lie", artist: "Shakira", year: 2006 },
  { title: "Waka Waka", artist: "Shakira", year: 2010 },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { title: "Somebody Told Me", artist: "The Killers", year: 2004 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", year: 2004 },
  { title: "American Idiot", artist: "Green Day", year: 2004 },
  { title: "Yellow", artist: "Coldplay", year: 2000 },
  { title: "The Scientist", artist: "Coldplay", year: 2002 },
  { title: "Clocks", artist: "Coldplay", year: 2002 },
  { title: "Fix You", artist: "Coldplay", year: 2005 },
  { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { title: "Speed of Sound", artist: "Coldplay", year: 2005 },
  { title: "Rehab", artist: "Amy Winehouse", year: 2006 },
  { title: "Back to Black", artist: "Amy Winehouse", year: 2006 },
  { title: "Valerie", artist: "Amy Winehouse", year: 2007 },
  { title: "She Will Be Loved", artist: "Maroon 5", year: 2004 },
  { title: "This Love", artist: "Maroon 5", year: 2002 },
  { title: "Hot in Herre", artist: "Nelly", year: 2002 },
  { title: "Dilemma", artist: "Nelly", year: 2002 },
  { title: "Survivor", artist: "Destiny's Child", year: 2001 },
  { title: "99 Problems", artist: "Jay-Z", year: 2003 },
  { title: "Gold Digger", artist: "Kanye West", year: 2005 },
  { title: "Stronger", artist: "Kanye West", year: 2007 },
  { title: "Heartless", artist: "Kanye West", year: 2008 },
  { title: "Drop It Like It's Hot", artist: "Snoop Dogg", year: 2004 },
  { title: "Where Is the Love?", artist: "Black Eyed Peas", year: 2003 },
  { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: 2009 },
  { title: "Boom Boom Pow", artist: "Black Eyed Peas", year: 2009 },
  { title: "Beautiful Day", artist: "U2", year: 2000 },
  { title: "One More Time", artist: "Daft Punk", year: 2000 },
  { title: "Maria Maria", artist: "Santana", year: 2000 },
  { title: "Gasolina", artist: "Daddy Yankee", year: 2004 },
  { title: "Party in the U.S.A.", artist: "Miley Cyrus", year: 2009 },
  { title: "Maneater", artist: "Nelly Furtado", year: 2006 },
  { title: "Promiscuous", artist: "Nelly Furtado", year: 2006 },
  { title: "Fergalicious", artist: "Fergie", year: 2006 },
  { title: "Empire State of Mind", artist: "Jay-Z", year: 2009 },
  { title: "Low", artist: "Flo Rida", year: 2007 },
  { title: "Right Round", artist: "Flo Rida", year: 2009 },

  // 2010s
  { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { title: "Someone Like You", artist: "Adele", year: 2011 },
  { title: "Hello", artist: "Adele", year: 2015 },
  { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2011 },
  { title: "Gangnam Style", artist: "PSY", year: 2012 },
  { title: "Thrift Shop", artist: "Macklemore & Ryan Lewis", year: 2012 },
  { title: "Royals", artist: "Lorde", year: 2013 },
  { title: "Happy", artist: "Pharrell Williams", year: 2013 },
  { title: "Uptown Funk", artist: "Mark Ronson", year: 2014 },
  { title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
  { title: "Blank Space", artist: "Taylor Swift", year: 2014 },
  { title: "Style", artist: "Taylor Swift", year: 2014 },
  { title: "Ready for It?", artist: "Taylor Swift", year: 2017 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
  { title: "Photograph", artist: "Ed Sheeran", year: 2015 },
  { title: "Perfect", artist: "Ed Sheeran", year: 2017 },
  { title: "Castle on the Hill", artist: "Ed Sheeran", year: 2017 },
  { title: "Sorry", artist: "Justin Bieber", year: 2015 },
  { title: "Love Yourself", artist: "Justin Bieber", year: 2015 },
  { title: "Baby", artist: "Justin Bieber", year: 2010 },
  { title: "Work", artist: "Rihanna", year: 2016 },
  { title: "Diamonds", artist: "Rihanna", year: 2012 },
  { title: "One Dance", artist: "Drake", year: 2016 },
  { title: "Hotline Bling", artist: "Drake", year: 2015 },
  { title: "God's Plan", artist: "Drake", year: 2018 },
  { title: "In My Feelings", artist: "Drake", year: 2018 },
  { title: "Despacito", artist: "Luis Fonsi", year: 2017 },
  { title: "Mi Gente", artist: "J Balvin", year: 2017 },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
  { title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
  { title: "Bury a Friend", artist: "Billie Eilish", year: 2019 },
  { title: "Señorita", artist: "Shawn Mendes", year: 2019 },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { title: "Can't Feel My Face", artist: "The Weeknd", year: 2015 },
  { title: "Starboy", artist: "The Weeknd", year: 2016 },
  { title: "Watermelon Sugar", artist: "Harry Styles", year: 2019 },
  { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },
  { title: "Moves Like Jagger", artist: "Maroon 5", year: 2011 },
  { title: "Animals", artist: "Maroon 5", year: 2014 },
  { title: "Firework", artist: "Katy Perry", year: 2010 },
  { title: "Roar", artist: "Katy Perry", year: 2013 },
  { title: "Teenage Dream", artist: "Katy Perry", year: 2010 },
  { title: "I Kissed a Girl", artist: "Katy Perry", year: 2008 },
  { title: "Dark Horse", artist: "Katy Perry", year: 2013 },
  { title: "Just the Way You Are", artist: "Bruno Mars", year: 2010 },
  { title: "Grenade", artist: "Bruno Mars", year: 2010 },
  { title: "Locked Out of Heaven", artist: "Bruno Mars", year: 2012 },
  { title: "24K Magic", artist: "Bruno Mars", year: 2016 },
  { title: "That's What I Like", artist: "Bruno Mars", year: 2016 },
  { title: "Super Bass", artist: "Nicki Minaj", year: 2010 },
  { title: "Anaconda", artist: "Nicki Minaj", year: 2014 },
  { title: "Thank U, Next", artist: "Ariana Grande", year: 2018 },
  { title: "7 Rings", artist: "Ariana Grande", year: 2019 },
  { title: "Problem", artist: "Ariana Grande", year: 2014 },
  { title: "Side to Side", artist: "Ariana Grande", year: 2016 },
  { title: "Wrecking Ball", artist: "Miley Cyrus", year: 2013 },
  { title: "Bodyak Yellow", artist: "Cardi B", year: 2017 },
  { title: "HUMBLE.", artist: "Kendrick Lamar", year: 2017 },
  { title: "Redbone", artist: "Childish Gambino", year: 2016 },
  { title: "Sicko Mode", artist: "Travis Scott", year: 2018 },
  { title: "Rockstar", artist: "Post Malone", year: 2017 },
  { title: "Sunflower", artist: "Post Malone", year: 2018 },
  { title: "Circles", artist: "Post Malone", year: 2019 },
  { title: "Young Dumb & Broke", artist: "Khalid", year: 2017 },
  { title: "Location", artist: "Khalid", year: 2016 },
  { title: "Wake Me Up", artist: "Avicii", year: 2013 },
  { title: "Levels", artist: "Avicii", year: 2011 },
  { title: "Hey Brother", artist: "Avicii", year: 2013 },
  { title: "Get Lucky", artist: "Daft Punk", year: 2013 },
  { title: "Lose Yourself to Dance", artist: "Daft Punk", year: 2013 },
  { title: "Don't You Worry Child", artist: "Swedish House Mafia", year: 2012 },
  { title: "Summer", artist: "Calvin Harris", year: 2014 },
  { title: "Feel So Close", artist: "Calvin Harris", year: 2011 },
  { title: "Titanium", artist: "David Guetta", year: 2011 },
  { title: "Closer", artist: "The Chainsmokers", year: 2016 },
  { title: "Something Just Like This", artist: "The Chainsmokers", year: 2017 },
  { title: "What Makes You Beautiful", artist: "One Direction", year: 2011 },
  { title: "Story of My Life", artist: "One Direction", year: 2013 },
  { title: "HUMBLE.", artist: "Kendrick Lamar", year: 2017 },
  { title: "It Was Always You", artist: "Maroon 5", year: 2014 },

  // 2020s
  { title: "Drivers License", artist: "Olivia Rodrigo", year: 2021 },
  { title: "good 4 u", artist: "Olivia Rodrigo", year: 2021 },
  { title: "Vampire", artist: "Olivia Rodrigo", year: 2023 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
  { title: "Physical", artist: "Dua Lipa", year: 2020 },
  { title: "As It Was", artist: "Harry Styles", year: 2022 },
  { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
  { title: "Unholy", artist: "Sam Smith", year: 2022 },
  { title: "About Damn Time", artist: "Lizzo", year: 2022 },
  { title: "Calm Down", artist: "Rema", year: 2022 },
  { title: "Heat Waves", artist: "Glass Animals", year: 2020 },
  { title: "Stay", artist: "The Kid LAROI", year: 2021 },
  { title: "Leave the Door Open", artist: "Silk Sonic", year: 2021 },
  { title: "Dynamite", artist: "BTS", year: 2020 },
  { title: "Butter", artist: "BTS", year: 2021 },
  { title: "Save Your Tears", artist: "The Weeknd", year: 2020 },
  { title: "Therefore I Am", artist: "Billie Eilish", year: 2020 },
  { title: "Happier Than Ever", artist: "Billie Eilish", year: 2021 },
  { title: "Cardigan", artist: "Taylor Swift", year: 2020 },
  { title: "Peaches", artist: "Justin Bieber", year: 2021 },
  { title: "Industry Baby", artist: "Lil Nas X", year: 2021 },
  { title: "Easy On Me", artist: "Adele", year: 2021 },
  { title: "Waterfall", artist: "Kygo", year: 2021 },
  { title: "Quevedo Bzrp Music Sessions", artist: "Bizarrap", year: 2022 },
  { title: "Tití Me Preguntó", artist: "Bad Bunny", year: 2022 },
  { title: "Kill Bill", artist: "SZA", year: 2022 },
  { title: "Calm Down", artist: "Selena Gomez", year: 2022 },
  { title: "Escapism", artist: "RAYE", year: 2022 },
  { title: "Unholy", artist: "Sam Smith", year: 2022 },
  { title: "Creepin'", artist: "Metro Boomin", year: 2022 },
  { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
  { title: "Ella Baila Sola", artist: "Eslabon Armado", year: 2023 },

  // ── Israeli / Hebrew songs ──────────────────────────────────────────────

  // Classics & Mizrahi
  { title: "Yerushalayim Shel Zahav", artist: "Shuli Natan", year: 1967 },
  { title: "Bashanah Haba'ah", artist: "Naomi Shemer", year: 1970 },
  { title: "Al Kol Eleh", artist: "Naomi Shemer", year: 1981 },
  { title: "Lu Yehi", artist: "Naomi Shemer", year: 1973 },
  { title: "Erev Shel Shoshanim", artist: "Shoshana Damari", year: 1958 },
  { title: "Yo Ya", artist: "Kaveret", year: 1973 },
  { title: "Poh Bli Ayin Ra", artist: "Kaveret", year: 1974 },
  { title: "Lo Haya Ve Lo Nihiye", artist: "Arik Einstein", year: 1971 },
  { title: "Ani Ve Ata", artist: "Arik Einstein", year: 1976 },
  { title: "Poshut Lihyot", artist: "Arik Einstein", year: 1985 },
  { title: "Shablool", artist: "Shalom Hanoch", year: 1970 },
  { title: "Ze Hazman", artist: "Shalom Hanoch", year: 1983 },
  { title: "Iti", artist: "Shalom Hanoch", year: 1977 },
  { title: "Lev Sheli", artist: "Yoni Rechter", year: 1976 },
  { title: "Shirim Nishkachim", artist: "Rami Kleinstein", year: 1990 },
  { title: "Kmo Geshem", artist: "Eyal Golan", year: 1996 },
  { title: "Eize Yom", artist: "Eyal Golan", year: 2001 },
  { title: "Ahava Shel Yakar", artist: "Eyal Golan", year: 2013 },
  { title: "Rakevet Layla", artist: "Sarit Hadad", year: 2002 },
  { title: "Hayu Zmanim", artist: "Sarit Hadad", year: 2011 },
  { title: "Hakol Over Habibi", artist: "Sarit Hadad", year: 2004 },
  { title: "Kmo She'ani", artist: "Kobi Peretz", year: 2008 },
  { title: "Mehake Lach", artist: "Kobi Peretz", year: 2011 },
  { title: "Balada La-Yam", artist: "Shlomo Artzi", year: 1976 },
  { title: "Tni Li Yad", artist: "Shlomo Artzi", year: 1988 },
  { title: "Etzlech Bavet", artist: "Shlomo Artzi", year: 1998 },
  { title: "Geshem", artist: "Shlomo Artzi", year: 2004 },
  { title: "Ha'ahava Hazot", artist: "Shlomo Artzi", year: 2004 },

  // Eurovision Israel
  { title: "A-Ba-Ni-Bi", artist: "Izhar Cohen", year: 1978 },
  { title: "Hallelujah", artist: "Gali Atari", year: 1979 },
  { title: "Diva", artist: "Dana International", year: 1998 },
  { title: "TOY", artist: "Netta", year: 2018 },

  // 1990s–2000s Israeli pop & rock
  { title: "Ze Lo Ani", artist: "Ehud Banai", year: 1998 },
  { title: "Hine Ani Ba", artist: "Ehud Banai", year: 1988 },
  { title: "Halev Sheli", artist: "HaYehudim", year: 1997 },
  { title: "Yom Huledet", artist: "HaYehudim", year: 1997 },
  { title: "Lehitorer", artist: "Ivri Lider", year: 2001 },
  { title: "Haim Sheli", artist: "Ivri Lider", year: 2001 },
  { title: "New Soul", artist: "Yael Naim", year: 2007 },
  { title: "Shirat Hasticker", artist: "HaDag Nachash", year: 2002 },
  { title: "Lo Hayiti Yodea", artist: "HaDag Nachash", year: 2007 },

  // Idan Raichel Project
  { title: "Im Tirtzeh", artist: "Idan Raichel Project", year: 2003 },
  { title: "Bo'i", artist: "Idan Raichel Project", year: 2006 },
  { title: "Kulam Yodim", artist: "Idan Raichel Project", year: 2006 },
  { title: "Lahavot", artist: "Idan Raichel", year: 2017 },

  // Infected Mushroom
  { title: "Becoming Insane", artist: "Infected Mushroom", year: 2007 },
  { title: "B.P. Empire", artist: "Infected Mushroom", year: 2000 },

  // Static & Ben El / Omer Adam / Modern Israeli pop
  { title: "Trumpiada", artist: "Static & Ben El Tavori", year: 2017 },
  { title: "Seret", artist: "Static & Ben El Tavori", year: 2020 },
  { title: "Milim", artist: "Omer Adam", year: 2016 },
  { title: "Neshama", artist: "Omer Adam", year: 2019 },
  { title: "Zman", artist: "Omer Adam", year: 2017 },
  { title: "10 Shanim", artist: "Omer Adam", year: 2021 },
  { title: "Ma Ata Yodea Alai", artist: "Moshe Peretz", year: 2011 },
  { title: "Ahavat Hayim", artist: "Moshe Peretz", year: 2015 },
  { title: "Neshika Bishvil Ha'or", artist: "Miri Mesika", year: 2003 },
  { title: "Yeladim Shel Ha'kayitz", artist: "Miri Mesika", year: 2010 },
  { title: "Bli Sof", artist: "Lior Narkis", year: 2007 },
  { title: "Ha'or She'becha", artist: "Lior Narkis", year: 2015 },
  { title: "Be'ein Iton", artist: "Rita", year: 1988 },
  { title: "Kama Tov She'Bata", artist: "Rita", year: 1993 },
  { title: "Yafim Haleilot", artist: "Rami Kleinstein", year: 2001 },

  // ── More Israeli bands & modern Israeli artists ─────────────────────────

  // HaDag Nachash (more)
  { title: "Zman Lehitorer", artist: "HaDag Nachash", year: 2000 },
  { title: "Mitamtem", artist: "HaDag Nachash", year: 2004 },
  { title: "California", artist: "HaDag Nachash", year: 2010 },
  { title: "Numi Numi", artist: "HaDag Nachash", year: 2010 },
  { title: "Hine Ani Ba", artist: "HaDag Nachash", year: 2012 },

  // Mashina
  { title: "Rakevet Layla LeKahir", artist: "Mashina", year: 1985 },
  { title: "Ein Li Eretz Acheret", artist: "Mashina", year: 1986 },
  { title: "Anachnu Ha-Sodot", artist: "Mashina", year: 1988 },
  { title: "Hatzbaut", artist: "Mashina", year: 1989 },
  { title: "Ahava Bat 17", artist: "Mashina", year: 1990 },
  { title: "Ha'Yom Yom Holedet", artist: "Mashina", year: 1991 },
  { title: "Shir Echad", artist: "Mashina", year: 1995 },
  { title: "Shir Achshav", artist: "Mashina", year: 2003 },

  // Teapacks (Tipex)
  { title: "Yoshvim BeBeit Kafe", artist: "Teapacks", year: 1995 },
  { title: "Salk Mimeni", artist: "Teapacks", year: 1996 },
  { title: "Push the Button", artist: "Teapacks", year: 2007 },
  { title: "Shir HaFreha", artist: "Teapacks", year: 2002 },
  { title: "Kvar Hayit Sham", artist: "Teapacks", year: 1998 },
  { title: "Ein Li Brera", artist: "Teapacks", year: 1996 },
  { title: "Yehoshua HaMelech", artist: "Teapacks", year: 2000 },

  // Kaveret (more)
  { title: "Shir HaMakolet", artist: "Kaveret", year: 1973 },
  { title: "Goliath", artist: "Kaveret", year: 1973 },
  { title: "Eih Sheh At Pasuk", artist: "Kaveret", year: 1974 },
  { title: "Yo Yah", artist: "Kaveret", year: 1973 },

  // Tislam
  { title: "Radio Hazak", artist: "Tislam", year: 1981 },
  { title: "Erev Erev", artist: "Tislam", year: 1981 },
  { title: "Sefer Tsofim", artist: "Tislam", year: 1983 },

  // Tamuz
  { title: "Shabbat Balaila", artist: "Tamuz", year: 1976 },
  { title: "End Of The Road", artist: "Tamuz", year: 1976 },

  // Benzin
  { title: "Sof Onat Hatapuzim", artist: "Benzin", year: 1982 },
  { title: "Ahuva Ha-Ktantonet", artist: "Benzin", year: 1984 },

  // Mosh Ben Ari / Sheva
  { title: "Salaam", artist: "Sheva", year: 2000 },
  { title: "Im Tirzu", artist: "Mosh Ben Ari", year: 2003 },
  { title: "Lalechet Sham", artist: "Mosh Ben Ari", year: 2005 },

  // Aviv Geffen
  { title: "Achshav Meunan", artist: "Aviv Geffen", year: 1992 },
  { title: "Pa'amayim Shesh", artist: "Aviv Geffen", year: 1995 },
  { title: "Yeladim Shel Hachayim", artist: "Aviv Geffen", year: 1996 },

  // Ehud Banai (more)
  { title: "Eretz Hadasha", artist: "Ehud Banai", year: 1993 },
  { title: "Ir Miklat", artist: "Ehud Banai", year: 1989 },
  { title: "Avraham", artist: "Ehud Banai", year: 1987 },

  // Berry Sakharof
  { title: "Hagiga Naki", artist: "Berry Sakharof", year: 1996 },
  { title: "Lo Maspik", artist: "Berry Sakharof", year: 2000 },
  { title: "Ze Doh", artist: "Berry Sakharof", year: 2004 },

  // Knesiyat Hasechel
  { title: "Shir Furim", artist: "Knesiyat Hasechel", year: 1998 },
  { title: "Yom Sasson", artist: "Knesiyat Hasechel", year: 2000 },
  { title: "Hatzi Manga", artist: "Knesiyat Hasechel", year: 1995 },

  // Monica Sex
  { title: "Atta Yode'a", artist: "Monica Sex", year: 1996 },
  { title: "Shavur Mehagil", artist: "Monica Sex", year: 1998 },

  // Mercedes Band
  { title: "She'i Shel", artist: "Mercedes Band", year: 2008 },

  // Yehuda Poliker
  { title: "Pachot Aval Ko'ev", artist: "Yehuda Poliker", year: 1988 },
  { title: "Mishehu Holech Tamid Iti", artist: "Yehuda Poliker", year: 1989 },

  // Meir Banai
  { title: "Shir Tikva", artist: "Meir Banai", year: 1993 },

  // Noa Kirel
  { title: "Million Dollar", artist: "Noa Kirel", year: 2019 },
  { title: "Trippy", artist: "Noa Kirel", year: 2020 },
  { title: "Bad Little Thing", artist: "Noa Kirel", year: 2019 },
  { title: "Please Don't Suck", artist: "Noa Kirel", year: 2021 },
  { title: "Unicorn", artist: "Noa Kirel", year: 2023 },
  { title: "Pouch", artist: "Noa Kirel", year: 2022 },

  // Tuna
  { title: "Pa'am Beshana", artist: "Tuna", year: 2019 },
  { title: "Anashim", artist: "Tuna", year: 2020 },
  { title: "Yom Yom", artist: "Tuna", year: 2018 },
  { title: "Hofesh", artist: "Tuna", year: 2021 },
  { title: "Lo Yode'a Lirkod", artist: "Tuna", year: 2022 },

  // Omer Adam (more)
  { title: "Tel Aviv", artist: "Omer Adam", year: 2014 },
  { title: "Bucharest", artist: "Omer Adam", year: 2017 },
  { title: "Shnei Meshugaim", artist: "Omer Adam", year: 2018 },
  { title: "Ana Be'Ahava", artist: "Omer Adam", year: 2020 },
  { title: "Sheli Latzemed", artist: "Omer Adam", year: 2022 },

  // Eden Hason
  { title: "Hi Sheli", artist: "Eden Hason", year: 2018 },
  { title: "Eich Ata Karov", artist: "Eden Hason", year: 2019 },
  { title: "Halayla", artist: "Eden Hason", year: 2020 },
  { title: "Ahavti Otach", artist: "Eden Hason", year: 2021 },

  // Eden Ben Zaken
  { title: "Melech HaOlam", artist: "Eden Ben Zaken", year: 2014 },
  { title: "Shabazi", artist: "Eden Ben Zaken", year: 2015 },

  // Eden Golan (Eurovision)
  { title: "Hurricane", artist: "Eden Golan", year: 2024 },

  // Anna Zak
  { title: "Yom Yom", artist: "Anna Zak", year: 2019 },
  { title: "Tikrah Li", artist: "Anna Zak", year: 2020 },

  // Stephane Legar
  { title: "Touchdown", artist: "Stephane Legar", year: 2018 },
  { title: "Eich Hi Holechet", artist: "Stephane Legar", year: 2019 },

  // Peer Tasi
  { title: "Tov Sheh Bata Habayta", artist: "Peer Tasi", year: 2014 },
  { title: "Layla", artist: "Peer Tasi", year: 2017 },
  { title: "Bahatzer Sheli", artist: "Peer Tasi", year: 2019 },

  // Itay Levi
  { title: "Tarara", artist: "Itay Levi", year: 2017 },
  { title: "Beoto Halayla", artist: "Itay Levi", year: 2019 },

  // Agam Buhbut
  { title: "Lehagshim", artist: "Agam Buhbut", year: 2018 },

  // Hanan Ben Ari
  { title: "Kacha Ze", artist: "Hanan Ben Ari", year: 2014 },
  { title: "Yeled Tov Yerushalayim", artist: "Hanan Ben Ari", year: 2016 },
  { title: "Shevet Ahim Veachayot", artist: "Hanan Ben Ari", year: 2018 },
  { title: "Hayinu Yeladim", artist: "Hanan Ben Ari", year: 2017 },

  // Ishay Ribo
  { title: "Seder HaAvoda", artist: "Ishay Ribo", year: 2017 },
  { title: "Tochi Ratsui", artist: "Ishay Ribo", year: 2018 },
  { title: "Hineh Yamim Ba'im", artist: "Ishay Ribo", year: 2019 },
  { title: "Keter Melucha", artist: "Ishay Ribo", year: 2021 },

  // Static & Ben El (more)
  { title: "Tudo Bom", artist: "Static & Ben El Tavori", year: 2018 },
  { title: "Im Atah Iti", artist: "Static & Ben El Tavori", year: 2019 },
  { title: "Shake Your Body", artist: "Static & Ben El Tavori", year: 2020 },
  { title: "Or Yarok", artist: "Static & Ben El Tavori", year: 2022 },

  // Subliminal
  { title: "Hatikva", artist: "Subliminal", year: 2002 },
  { title: "Biladayich", artist: "Subliminal", year: 2004 },

  // Hadag Nachash collaborations / other modern hip-hop
  { title: "Hu Lo Yada Et Shma", artist: "Shabak Samech", year: 2003 },
  { title: "Chaiim Tovim", artist: "Shabak Samech", year: 2005 },

  // Marina Maximilian
  { title: "Achshav Tov", artist: "Marina Maximilian", year: 2009 },
  { title: "Im Tafsiki", artist: "Marina Maximilian", year: 2015 },

  // Dudu Tassa
  { title: "Yossi", artist: "Dudu Tassa", year: 2011 },
  { title: "Habubot Shel Paco", artist: "Dudu Tassa", year: 2008 },

  // Idan Amedi
  { title: "Be'emtsa Halayla", artist: "Idan Amedi", year: 2013 },
  { title: "Etmol Hayinu Yeladim", artist: "Idan Amedi", year: 2016 },

  // Asaf Avidan
  { title: "Reckoning Song (One Day)", artist: "Asaf Avidan", year: 2008 },
  { title: "Different Pulses", artist: "Asaf Avidan", year: 2012 },

  // Ninet Tayeb
  { title: "Yesh Bi Ahava", artist: "Ninet Tayeb", year: 2004 },
  { title: "Strong Sometimes", artist: "Ninet Tayeb", year: 2014 },

  // Yardena Arazi
  { title: "Chai", artist: "Ofra Haza", year: 1983 },
  { title: "Im Nin'Alu", artist: "Ofra Haza", year: 1988 },

  // Zehava Ben
  { title: "Tipat Mazal", artist: "Zehava Ben", year: 1992 },

  // Daklon
  { title: "Tachat Shmei Yam HaTichon", artist: "Daklon", year: 1985 },

  // Margalit Tzan'ani
  { title: "Shir Ahava Bedoui", artist: "Margalit Tzan'ani", year: 1990 },
  { title: "Le'an Halachta Yaldi", artist: "Margalit Tzan'ani", year: 1992 },

  // Boaz Sharabi
  { title: "Ten Li Yad", artist: "Boaz Sharabi", year: 1981 },
  { title: "Geshem Bo'er", artist: "Boaz Sharabi", year: 1990 },

  // Zohar Argov
  { title: "Haperach Begani", artist: "Zohar Argov", year: 1982 },
  { title: "Elinor", artist: "Zohar Argov", year: 1983 },

  // Avihu Medina
  { title: "Shabchei Yerushalayim", artist: "Avihu Medina", year: 1980 },

  // Eyal Golan (more)
  { title: "Ima Sheli", artist: "Eyal Golan", year: 2007 },
  { title: "Mishehu Holech Iti Tamid", artist: "Eyal Golan", year: 2010 },

  // Hovi Star
  { title: "Made of Stars", artist: "Hovi Star", year: 2016 },

  // Nasrin Kadri
  { title: "Habibi", artist: "Nasrin Kadri", year: 2016 },

  // E-Z
  { title: "Shir Sameach", artist: "E-Z", year: 2019 },

  // Jasmin Moallem
  { title: "Bo Higia Hazman", artist: "Jasmin Moallem", year: 2015 },
  { title: "HaKol Over", artist: "Jasmin Moallem", year: 2014 },

  // Nathan Goshen
  { title: "Yamim Atzlanim", artist: "Nathan Goshen", year: 2014 },
  { title: "Tagidi Shtuyot", artist: "Nathan Goshen", year: 2015 },

  // Mergui
  { title: "Yamim Yafim", artist: "Mergui", year: 2020 },

  // Dean Miari
  { title: "Hadracha", artist: "Dean Miari", year: 2022 },
];

module.exports = SONGS;
