// Deck 2 — 300 curated songs, different from Deck 1
// Spans 1950s–2024, multiple genres and regions

const SONGS2 = [
  // ── 1950s ────────────────────────────────────────────────────────────────
  { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", year: 1954 },
  { title: "Blueberry Hill", artist: "Fats Domino", year: 1956 },
  { title: "That'll Be the Day", artist: "Buddy Holly", year: 1957 },
  { title: "Peggy Sue", artist: "Buddy Holly", year: 1957 },
  { title: "Why Do Fools Fall in Love", artist: "Frankie Lymon", year: 1956 },
  { title: "Sh-Boom (Life Could Be a Dream)", artist: "The Chords", year: 1954 },
  { title: "At the Hop", artist: "Danny & the Juniors", year: 1957 },
  { title: "Yakety Yak", artist: "The Coasters", year: 1958 },
  { title: "Charlie Brown", artist: "The Coasters", year: 1959 },
  { title: "Everyday", artist: "Buddy Holly", year: 1957 },

  // ── Soul / Motown ─────────────────────────────────────────────────────────
  { title: "(Sittin' On) The Dock of the Bay", artist: "Otis Redding", year: 1968 },
  { title: "Try a Little Tenderness", artist: "Otis Redding", year: 1966 },
  { title: "I've Been Loving You Too Long", artist: "Otis Redding", year: 1965 },
  { title: "I Got You (I Feel Good)", artist: "James Brown", year: 1965 },
  { title: "Papa's Got a Brand New Bag", artist: "James Brown", year: 1965 },
  { title: "Get Up (I Feel Like Being a) Sex Machine", artist: "James Brown", year: 1970 },
  { title: "What'd I Say", artist: "Ray Charles", year: 1959 },
  { title: "Hit the Road Jack", artist: "Ray Charles", year: 1961 },
  { title: "Georgia on My Mind", artist: "Ray Charles", year: 1960 },
  { title: "You Send Me", artist: "Sam Cooke", year: 1957 },
  { title: "Wonderful World", artist: "Sam Cooke", year: 1960 },
  { title: "A Change Is Gonna Come", artist: "Sam Cooke", year: 1964 },
  { title: "My Girl", artist: "The Temptations", year: 1964 },
  { title: "Papa Was a Rollin' Stone", artist: "The Temptations", year: 1972 },
  { title: "Ain't Too Proud to Beg", artist: "The Temptations", year: 1966 },
  { title: "Baby Love", artist: "The Supremes", year: 1964 },
  { title: "Stop! In the Name of Love", artist: "The Supremes", year: 1965 },
  { title: "You Keep Me Hangin' On", artist: "The Supremes", year: 1966 },
  { title: "Higher Ground", artist: "Stevie Wonder", year: 1973 },
  { title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder", year: 1970 },
  { title: "Overjoyed", artist: "Stevie Wonder", year: 1985 },
  { title: "Let's Get It On", artist: "Marvin Gaye", year: 1973 },
  { title: "Sexual Healing", artist: "Marvin Gaye", year: 1982 },
  { title: "Heard It Through the Grapevine", artist: "Marvin Gaye", year: 1968 },
  { title: "Tired of Being Alone", artist: "Al Green", year: 1971 },
  { title: "Let's Stay Together", artist: "Al Green", year: 1971 },
  { title: "Think", artist: "Aretha Franklin", year: 1968 },
  { title: "Chain of Fools", artist: "Aretha Franklin", year: 1967 },
  { title: "I Say a Little Prayer", artist: "Aretha Franklin", year: 1968 },
  { title: "Mustang Sally", artist: "Wilson Pickett", year: 1966 },
  { title: "In the Midnight Hour", artist: "Wilson Pickett", year: 1965 },

  // ── Classic Rock / 1960s–70s ──────────────────────────────────────────────
  { title: "Light My Fire", artist: "The Doors", year: 1967 },
  { title: "Riders on the Storm", artist: "The Doors", year: 1971 },
  { title: "People Are Strange", artist: "The Doors", year: 1967 },
  { title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Proud Mary", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Have You Ever Seen the Rain", artist: "Creedence Clearwater Revival", year: 1971 },
  { title: "You Really Got Me", artist: "The Kinks", year: 1964 },
  { title: "Lola", artist: "The Kinks", year: 1970 },
  { title: "Sunny Afternoon", artist: "The Kinks", year: 1966 },
  { title: "Brown Eyed Girl", artist: "Van Morrison", year: 1967 },
  { title: "Moondance", artist: "Van Morrison", year: 1970 },
  { title: "Into the Mystic", artist: "Van Morrison", year: 1970 },
  { title: "Voodoo Child (Slight Return)", artist: "Jimi Hendrix", year: 1968 },
  { title: "Hey Joe", artist: "Jimi Hendrix", year: 1966 },
  { title: "Rock and Roll", artist: "Led Zeppelin", year: 1971 },
  { title: "Immigrant Song", artist: "Led Zeppelin", year: 1970 },
  { title: "Tangerine", artist: "Led Zeppelin", year: 1971 },
  { title: "Miss You", artist: "The Rolling Stones", year: 1978 },
  { title: "Start Me Up", artist: "The Rolling Stones", year: 1981 },
  { title: "Wild Horses", artist: "The Rolling Stones", year: 1971 },
  { title: "Free Fallin'", artist: "Tom Petty", year: 1989 },
  { title: "American Girl", artist: "Tom Petty", year: 1977 },
  { title: "I Won't Back Down", artist: "Tom Petty", year: 1989 },
  { title: "Peaceful Easy Feeling", artist: "Eagles", year: 1972 },
  { title: "Desperado", artist: "Eagles", year: 1973 },
  { title: "Take It Easy", artist: "Eagles", year: 1972 },
  { title: "The Chain", artist: "Fleetwood Mac", year: 1977 },
  { title: "Oh Well", artist: "Fleetwood Mac", year: 1969 },
  { title: "Sara", artist: "Fleetwood Mac", year: 1979 },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974 },
  { title: "Free Bird", artist: "Lynyrd Skynyrd", year: 1973 },
  { title: "Piano Man", artist: "Billy Joel", year: 1973 },
  { title: "It's Still Rock and Roll to Me", artist: "Billy Joel", year: 1980 },
  { title: "We Didn't Start the Fire", artist: "Billy Joel", year: 1989 },
  { title: "Uptown Girl", artist: "Billy Joel", year: 1983 },
  { title: "Maggie May", artist: "Rod Stewart", year: 1971 },
  { title: "Do Ya Think I'm Sexy?", artist: "Rod Stewart", year: 1978 },
  { title: "Wild World", artist: "Cat Stevens", year: 1970 },
  { title: "Father and Son", artist: "Cat Stevens", year: 1970 },
  { title: "Fire and Rain", artist: "James Taylor", year: 1970 },
  { title: "You've Got a Friend", artist: "James Taylor", year: 1971 },
  { title: "I Feel the Earth Move", artist: "Carole King", year: 1971 },
  { title: "So Far Away", artist: "Carole King", year: 1971 },
  { title: "The Boxer", artist: "Simon & Garfunkel", year: 1969 },
  { title: "America", artist: "Simon & Garfunkel", year: 1968 },
  { title: "Homeward Bound", artist: "Simon & Garfunkel", year: 1966 },

  // ── 70s–80s ───────────────────────────────────────────────────────────────
  { title: "Hot Stuff", artist: "Donna Summer", year: 1979 },
  { title: "I Feel Love", artist: "Donna Summer", year: 1977 },
  { title: "Last Dance", artist: "Donna Summer", year: 1978 },
  { title: "Can't Get Enough of Your Love, Babe", artist: "Barry White", year: 1974 },
  { title: "I'm Gonna Love You Just a Little More Baby", artist: "Barry White", year: 1973 },
  { title: "I Want You Back", artist: "Jackson 5", year: 1969 },
  { title: "ABC", artist: "Jackson 5", year: 1970 },
  { title: "I'll Be There", artist: "Jackson 5", year: 1970 },
  { title: "Psycho Killer", artist: "Talking Heads", year: 1977 },
  { title: "Once in a Lifetime", artist: "Talking Heads", year: 1980 },
  { title: "Burning Down the House", artist: "Talking Heads", year: 1983 },
  { title: "Lovesong", artist: "The Cure", year: 1989 },
  { title: "Boys Don't Cry", artist: "The Cure", year: 1979 },
  { title: "Close to Me", artist: "The Cure", year: 1985 },
  { title: "Personal Jesus", artist: "Depeche Mode", year: 1989 },
  { title: "Enjoy the Silence", artist: "Depeche Mode", year: 1990 },
  { title: "Just Can't Get Enough", artist: "Depeche Mode", year: 1981 },
  { title: "Blue Monday", artist: "New Order", year: 1983 },
  { title: "Bizarre Love Triangle", artist: "New Order", year: 1986 },
  { title: "Love Will Tear Us Apart", artist: "Joy Division", year: 1980 },
  { title: "She's Lost Control", artist: "Joy Division", year: 1979 },
  { title: "London Calling", artist: "The Clash", year: 1979 },
  { title: "Rock the Casbah", artist: "The Clash", year: 1982 },
  { title: "Heart of Glass", artist: "Blondie", year: 1979 },
  { title: "Call Me", artist: "Blondie", year: 1980 },
  { title: "Hungry Like the Wolf", artist: "Duran Duran", year: 1982 },
  { title: "Rio", artist: "Duran Duran", year: 1982 },
  { title: "Shout", artist: "Tears for Fears", year: 1984 },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", year: 1985 },
  { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: 1983 },
  { title: "Here Comes the Rain Again", artist: "Eurythmics", year: 1984 },
  { title: "What's Love Got to Do with It", artist: "Tina Turner", year: 1984 },
  { title: "Simply the Best", artist: "Tina Turner", year: 1989 },
  { title: "Hello", artist: "Lionel Richie", year: 1984 },
  { title: "All Night Long (All Night)", artist: "Lionel Richie", year: 1983 },
  { title: "Dancing on the Ceiling", artist: "Lionel Richie", year: 1986 },
  { title: "Hit Me with Your Best Shot", artist: "Pat Benatar", year: 1980 },
  { title: "Love Is a Battlefield", artist: "Pat Benatar", year: 1983 },
  { title: "I Love Rock 'n' Roll", artist: "Joan Jett", year: 1982 },
  { title: "Bad Reputation", artist: "Joan Jett", year: 1980 },
  { title: "Need You Tonight", artist: "INXS", year: 1987 },
  { title: "Never Tear Us Apart", artist: "INXS", year: 1988 },
  { title: "Eternal Flame", artist: "The Bangles", year: 1988 },
  { title: "Walk Like an Egyptian", artist: "The Bangles", year: 1986 },
  { title: "Dancing in the Dark", artist: "Bruce Springsteen", year: 1984 },
  { title: "The River", artist: "Bruce Springsteen", year: 1980 },
  { title: "White Wedding", artist: "Billy Idol", year: 1982 },
  { title: "Rebel Yell", artist: "Billy Idol", year: 1983 },
  { title: "In the Air Tonight", artist: "Genesis", year: 1981 },
  { title: "Sledgehammer", artist: "Peter Gabriel", year: 1986 },
  { title: "Solsbury Hill", artist: "Peter Gabriel", year: 1977 },
  { title: "Tom Sawyer", artist: "Rush", year: 1981 },
  { title: "The Spirit of Radio", artist: "Rush", year: 1980 },
  { title: "More Than a Feeling", artist: "Boston", year: 1976 },
  { title: "I Want to Know What Love Is", artist: "Foreigner", year: 1984 },
  { title: "Can't Fight This Feeling", artist: "REO Speedwagon", year: 1984 },
  { title: "Keep On Loving You", artist: "REO Speedwagon", year: 1980 },
  { title: "25 or 6 to 4", artist: "Chicago", year: 1970 },
  { title: "If You Leave Me Now", artist: "Chicago", year: 1976 },
  { title: "The Joker", artist: "Steve Miller Band", year: 1973 },
  { title: "Fly Like an Eagle", artist: "Steve Miller Band", year: 1976 },
  { title: "Dust in the Wind", artist: "Kansas", year: 1977 },
  { title: "Edge of Seventeen", artist: "Stevie Nicks", year: 1982 },
  { title: "Stand Back", artist: "Stevie Nicks", year: 1983 },

  // ── 90s Pop / Dance / R&B ─────────────────────────────────────────────────
  { title: "The Sign", artist: "Ace of Base", year: 1993 },
  { title: "All That She Wants", artist: "Ace of Base", year: 1992 },
  { title: "The Look", artist: "Roxette", year: 1988 },
  { title: "It Must Have Been Love", artist: "Roxette", year: 1990 },
  { title: "It Wasn't Me", artist: "Shaggy", year: 2000 },
  { title: "Boombastic", artist: "Shaggy", year: 1995 },
  { title: "End of the Road", artist: "Boyz II Men", year: 1992 },
  { title: "I'll Make Love to You", artist: "Boyz II Men", year: 1994 },
  { title: "One Sweet Day", artist: "Mariah Carey", year: 1995 },
  { title: "Hero", artist: "Mariah Carey", year: 1993 },
  { title: "Fantasy", artist: "Mariah Carey", year: 1995 },
  { title: "Emotions", artist: "Mariah Carey", year: 1991 },
  { title: "Together Again", artist: "Janet Jackson", year: 1997 },
  { title: "That's the Way Love Goes", artist: "Janet Jackson", year: 1993 },
  { title: "Just a Girl", artist: "No Doubt", year: 1995 },
  { title: "Don't Speak", artist: "No Doubt", year: 1995 },
  { title: "Loser", artist: "Beck", year: 1994 },
  { title: "Buddy Holly", artist: "Weezer", year: 1994 },
  { title: "Undone – The Sweater Song", artist: "Weezer", year: 1994 },
  { title: "Santeria", artist: "Sublime", year: 1996 },
  { title: "What I Got", artist: "Sublime", year: 1996 },
  { title: "Crash into Me", artist: "Dave Matthews Band", year: 1996 },
  { title: "Hold My Hand", artist: "Hootie & the Blowfish", year: 1994 },
  { title: "3 AM", artist: "Matchbox Twenty", year: 1996 },
  { title: "Push", artist: "Matchbox Twenty", year: 1996 },
  { title: "Drops of Jupiter", artist: "Train", year: 2001 },
  { title: "Truly Madly Deeply", artist: "Savage Garden", year: 1997 },
  { title: "U Can't Touch This", artist: "MC Hammer", year: 1990 },
  { title: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990 },
  { title: "Push It", artist: "Salt-N-Pepa", year: 1987 },
  { title: "Whatta Man", artist: "Salt-N-Pepa", year: 1993 },
  { title: "Hold On", artist: "En Vogue", year: 1990 },
  { title: "Free Your Mind", artist: "En Vogue", year: 1992 },
  { title: "Macarena", artist: "Los Del Rio", year: 1993 },
  { title: "Barbie Girl", artist: "Aqua", year: 1997 },
  { title: "What Is Love", artist: "Haddaway", year: 1993 },
  { title: "Blue (Da Ba Dee)", artist: "Eiffel 65", year: 1998 },
  { title: "Firestarter", artist: "Prodigy", year: 1996 },
  { title: "Breathe", artist: "Prodigy", year: 1996 },
  { title: "The Rockafeller Skank", artist: "Fatboy Slim", year: 1998 },
  { title: "Praise You", artist: "Fatboy Slim", year: 1998 },
  { title: "Insomnia", artist: "Faithless", year: 1995 },
  { title: "Where's Your Head At", artist: "Basement Jaxx", year: 2001 },
  { title: "Block Rockin' Beats", artist: "Chemical Brothers", year: 1997 },

  // ── 2000s Indie / Alt ─────────────────────────────────────────────────────
  { title: "Last Nite", artist: "The Strokes", year: 2001 },
  { title: "Reptilia", artist: "The Strokes", year: 2003 },
  { title: "Seven Nation Army", artist: "White Stripes", year: 2003 },
  { title: "Icky Thump", artist: "White Stripes", year: 2007 },
  { title: "I Bet You Look Good on the Dancefloor", artist: "Arctic Monkeys", year: 2005 },
  { title: "R U Mine?", artist: "Arctic Monkeys", year: 2012 },
  { title: "Do I Wanna Know?", artist: "Arctic Monkeys", year: 2013 },
  { title: "Take Me Out", artist: "Franz Ferdinand", year: 2004 },
  { title: "Do You Want To", artist: "Franz Ferdinand", year: 2004 },
  { title: "Sex on Fire", artist: "Kings of Leon", year: 2008 },
  { title: "Use Somebody", artist: "Kings of Leon", year: 2008 },
  { title: "Supermassive Black Hole", artist: "Muse", year: 2006 },
  { title: "Uprising", artist: "Muse", year: 2009 },
  { title: "Human", artist: "The Killers", year: 2008 },
  { title: "All These Things That I've Done", artist: "The Killers", year: 2004 },
  { title: "Feel Good Inc.", artist: "Gorillaz", year: 2005 },
  { title: "Clint Eastwood", artist: "Gorillaz", year: 2001 },
  { title: "In the End", artist: "Linkin Park", year: 2000 },
  { title: "Numb", artist: "Linkin Park", year: 2003 },
  { title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006 },
  { title: "Helena", artist: "My Chemical Romance", year: 2004 },
  { title: "Sugar We're Goin Down", artist: "Fall Out Boy", year: 2005 },
  { title: "Thnks fr th Mmrs", artist: "Fall Out Boy", year: 2007 },
  { title: "Misery Business", artist: "Paramore", year: 2007 },
  { title: "Decode", artist: "Paramore", year: 2008 },
  { title: "I Write Sins Not Tragedies", artist: "Panic! at the Disco", year: 2005 },
  { title: "Bring Me to Life", artist: "Evanescence", year: 2003 },
  { title: "My Immortal", artist: "Evanescence", year: 2003 },
  { title: "Banana Pancakes", artist: "Jack Johnson", year: 2005 },
  { title: "I'm Yours", artist: "Jason Mraz", year: 2008 },
  { title: "You're Beautiful", artist: "James Blunt", year: 2004 },
  { title: "Chasing Cars", artist: "Snow Patrol", year: 2006 },
  { title: "Somewhere a Clock Is Ticking", artist: "Snow Patrol", year: 2006 },
  { title: "Somewhere Only We Know", artist: "Keane", year: 2004 },
  { title: "Everybody's Changing", artist: "Keane", year: 2003 },
  { title: "How to Save a Life", artist: "The Fray", year: 2005 },

  // ── Electronic / Dance 2010s ──────────────────────────────────────────────
  { title: "The Nights", artist: "Avicii", year: 2014 },
  { title: "Without You", artist: "Avicii", year: 2011 },
  { title: "Don't You Worry Child", artist: "Swedish House Mafia", year: 2012 },
  { title: "Save the World", artist: "Swedish House Mafia", year: 2011 },
  { title: "Firestone", artist: "Kygo", year: 2015 },
  { title: "Stole the Show", artist: "Kygo", year: 2015 },
  { title: "Say It", artist: "Flume", year: 2016 },
  { title: "Skin", artist: "Flume", year: 2016 },
  { title: "Divide", artist: "Odesza", year: 2014 },
  { title: "White Lies", artist: "Disclosure", year: 2012 },
  { title: "Latch", artist: "Disclosure", year: 2012 },
  { title: "Rather Be", artist: "Clean Bandit", year: 2014 },
  { title: "Rockabye", artist: "Clean Bandit", year: 2016 },
  { title: "Chandelier", artist: "Sia", year: 2014 },
  { title: "Elastic Heart", artist: "Sia", year: 2014 },
  { title: "Cheap Thrills", artist: "Sia", year: 2016 },

  // ── Hip-Hop 2010s–2020s ───────────────────────────────────────────────────
  { title: "Swimming Pools (Drank)", artist: "Kendrick Lamar", year: 2012 },
  { title: "DNA.", artist: "Kendrick Lamar", year: 2017 },
  { title: "Money Trees", artist: "Kendrick Lamar", year: 2012 },
  { title: "No Role Modelz", artist: "J. Cole", year: 2014 },
  { title: "Middle Child", artist: "J. Cole", year: 2019 },
  { title: "See You Again", artist: "Wiz Khalifa", year: 2015 },
  { title: "Black and Yellow", artist: "Wiz Khalifa", year: 2010 },
  { title: "Empire State of Mind", artist: "Alicia Keys", year: 2009 },
  { title: "If I Ain't Got You", artist: "Alicia Keys", year: 2003 },
  { title: "No One", artist: "Alicia Keys", year: 2007 },
  { title: "All of Me", artist: "John Legend", year: 2013 },
  { title: "Ordinary People", artist: "John Legend", year: 2004 },
  { title: "WAP", artist: "Cardi B", year: 2020 },
  { title: "I Like It", artist: "Cardi B", year: 2018 },
  { title: "Goosebumps", artist: "Travis Scott", year: 2016 },
  { title: "HIGHEST IN THE ROOM", artist: "Travis Scott", year: 2019 },
  { title: "Lucid Dreams", artist: "Juice WRLD", year: 2018 },
  { title: "Legends", artist: "Juice WRLD", year: 2019 },
  { title: "Yes Indeed", artist: "Lil Baby", year: 2018 },
  { title: "Drip Too Hard", artist: "Lil Baby", year: 2018 },
  { title: "Bad and Boujee", artist: "Migos", year: 2016 },
  { title: "Walk It Talk It", artist: "Migos", year: 2018 },
  { title: "Bank Account", artist: "21 Savage", year: 2017 },
  { title: "Rockstar", artist: "21 Savage", year: 2017 },
  { title: "Mask Off", artist: "Future", year: 2017 },
  { title: "Life Is Good", artist: "Future", year: 2020 },
  { title: "Wyclef Jean", artist: "Young Thug", year: 2016 },
  { title: "Best Friend", artist: "Young Thug", year: 2016 },
  { title: "XO TOUR Llif3", artist: "Lil Uzi Vert", year: 2017 },
  { title: "Just Wanna Rock", artist: "Lil Uzi Vert", year: 2022 },
  { title: "A Milli", artist: "Lil Wayne", year: 2008 },
  { title: "6 Foot 7 Foot", artist: "Lil Wayne", year: 2011 },
  { title: "Starships", artist: "Nicki Minaj", year: 2012 },
  { title: "Only", artist: "Nicki Minaj", year: 2014 },

  // ── Latin ─────────────────────────────────────────────────────────────────
  { title: "If You Had My Love", artist: "Jennifer Lopez", year: 1999 },
  { title: "On the Floor", artist: "Jennifer Lopez", year: 2011 },
  { title: "Vivir Mi Vida", artist: "Marc Anthony", year: 2013 },
  { title: "Valió la Pena", artist: "Marc Anthony", year: 2000 },
  { title: "Con Calma", artist: "Daddy Yankee", year: 2019 },
  { title: "Shaky Shaky", artist: "Daddy Yankee", year: 2016 },
  { title: "Safari", artist: "J Balvin", year: 2016 },
  { title: "Reggaeton", artist: "J Balvin", year: 2018 },
  { title: "Dakiti", artist: "Bad Bunny", year: 2020 },
  { title: "Yonaguni", artist: "Bad Bunny", year: 2021 },
  { title: "Hawái", artist: "Maluma", year: 2020 },
  { title: "Felices los 4", artist: "Maluma", year: 2017 },
  { title: "Tusa", artist: "Karol G", year: 2019 },
  { title: "Bichota", artist: "Karol G", year: 2020 },
  { title: "Dile Que Tu Me Quieres", artist: "Ozuna", year: 2017 },
  { title: "Criminal", artist: "Ozuna", year: 2017 },
  { title: "Malamente", artist: "Rosalía", year: 2017 },
  { title: "Con Altura", artist: "Rosalía", year: 2019 },
  { title: "Vida de Rico", artist: "Camilo", year: 2020 },
  { title: "Favorito", artist: "Camilo", year: 2020 },

  // ── Country ───────────────────────────────────────────────────────────────
  { title: "The Gambler", artist: "Kenny Rogers", year: 1978 },
  { title: "Islands in the Stream", artist: "Kenny Rogers", year: 1983 },
  { title: "Friends in Low Places", artist: "Garth Brooks", year: 1990 },
  { title: "The Dance", artist: "Garth Brooks", year: 1990 },
  { title: "Live Like You Were Dying", artist: "Tim McGraw", year: 2004 },
  { title: "Humble and Kind", artist: "Tim McGraw", year: 2015 },
  { title: "Breathe", artist: "Faith Hill", year: 1999 },
  { title: "This Kiss", artist: "Faith Hill", year: 1998 },
  { title: "Rainbow", artist: "Kacey Musgraves", year: 2018 },
  { title: "Golden Hour", artist: "Kacey Musgraves", year: 2018 },
  { title: "Whiskey Glasses", artist: "Morgan Wallen", year: 2018 },
  { title: "Wasted on You", artist: "Morgan Wallen", year: 2021 },
  { title: "Beautiful Crazy", artist: "Luke Combs", year: 2018 },
  { title: "When It Rains It Pours", artist: "Luke Combs", year: 2017 },
  { title: "Meant to Be", artist: "Florida Georgia Line", year: 2017 },
  { title: "Cruise", artist: "Florida Georgia Line", year: 2012 },

  // ── Indie / Alternative 2010s–2020s ──────────────────────────────────────
  { title: "Lost in Translation", artist: "Tame Impala", year: 2012 },
  { title: "The Less I Know the Better", artist: "Tame Impala", year: 2015 },
  { title: "New Person, Same Old Mistakes", artist: "Tame Impala", year: 2015 },
  { title: "Pumped Up Kicks", artist: "Foster the People", year: 2011 },
  { title: "We Are Young", artist: "fun.", year: 2011 },
  { title: "Carry On", artist: "fun.", year: 2012 },
  { title: "Kids", artist: "MGMT", year: 2007 },
  { title: "Electric Feel", artist: "MGMT", year: 2007 },
  { title: "Shut Up and Dance", artist: "Walk the Moon", year: 2014 },
  { title: "Radioactive", artist: "Imagine Dragons", year: 2012 },
  { title: "Demons", artist: "Imagine Dragons", year: 2013 },
  { title: "Thunder", artist: "Imagine Dragons", year: 2017 },
  { title: "Stressed Out", artist: "Twenty One Pilots", year: 2015 },
  { title: "Ride", artist: "Twenty One Pilots", year: 2015 },
  { title: "Take Me to Church", artist: "Hozier", year: 2013 },
  { title: "Budapest", artist: "George Ezra", year: 2014 },
  { title: "Shotgun", artist: "George Ezra", year: 2018 },
  { title: "Holiday", artist: "Vampire Weekend", year: 2013 },
  { title: "A-Punk", artist: "Vampire Weekend", year: 2008 },
  { title: "Shake Me Down", artist: "Cage the Elephant", year: 2011 },
  { title: "Ain't No Rest for the Wicked", artist: "Cage the Elephant", year: 2008 },

  // ── More 2020s ────────────────────────────────────────────────────────────
  { title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", year: 2021 },
  { title: "shivers", artist: "Ed Sheeran", year: 2021 },
  { title: "Overpass Graffiti", artist: "Ed Sheeran", year: 2021 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "Arcade", artist: "Duncan Laurence", year: 2019 },
  { title: "Astronaut in the Ocean", artist: "Masked Wolf", year: 2019 },
  { title: "Made You Look", artist: "Meghan Trainor", year: 2022 },
  { title: "About Damn Time", artist: "Lizzo", year: 2022 },
  { title: "Ghost", artist: "Justin Bieber", year: 2021 },
  { title: "Essence", artist: "Wizkid", year: 2020 },
  { title: "Running Up That Hill (A Deal with God)", artist: "Kate Bush", year: 1985 },
  { title: "Woman", artist: "Doja Cat", year: 2021 },
  { title: "Kiss Me More", artist: "Doja Cat", year: 2021 },
  { title: "Golden", artist: "Harry Styles", year: 2020 },
  { title: "Midnight Rain", artist: "Taylor Swift", year: 2022 },
  { title: "Snow on the Beach", artist: "Taylor Swift", year: 2022 },
  { title: "Karma", artist: "Taylor Swift", year: 2022 },
  { title: "Superhero (Heroes & Villains)", artist: "Metro Boomin", year: 2022 },
  { title: "Rich Flex", artist: "Drake", year: 2022 },
  { title: "Cuff It", artist: "Beyoncé", year: 2022 },
  { title: "Break My Soul", artist: "Beyoncé", year: 2022 },
  { title: "Moth to a Flame", artist: "Swedish House Mafia", year: 2021 },
  { title: "Ghost / Empty", artist: "Justin Bieber", year: 2021 },
  { title: "Escapism", artist: "RAYE", year: 2022 },
  { title: "Mañana Será Bonito", artist: "Karol G", year: 2023 },
  { title: "Des/Afortunado", artist: "Camilo", year: 2023 },

];

module.exports = SONGS2;
